table 'Arrangement Type'
	lineageTag: c7cb613d-9d95-4212-99b0-afeb17ed7411

	column ChildInvolvement
		dataType: string
		isHidden
		lineageTag: 106f4bcb-6fa8-4ebc-a504-f2cad0bf9090
		summarizeBy: none
		sourceColumn: ChildInvolvement

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Arrangement Type'
		dataType: string
		lineageTag: 43965f59-42d2-47e8-ba87-6943e599d63a
		summarizeBy: none
		sourceColumn: Arrangement Type

		annotation SummarizationSetBy = Automatic

	partition 'Arrangement Type-597c3ca7-59e2-4e86-8453-c8def7291a36' = m
		mode: import
		queryGroup: 'Model Queries'
		source = ```
				let
				    Source = #"OData Live",
				    SourceTable = Source{[Name="ArrangementType",Signature="table"]}[Data],
				
				    ArrangementType = 
				    Table.SelectColumns(
				        Table.RenameColumns(
				            SourceTable,
				            {{"Type", "Arrangement Type"}}
				        ),
				        {"Arrangement Type", "ChildInvolvement"}
				    )
				in
				    ArrangementType
				```

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

