table Arrangement
	lineageTag: 46d5bd4a-a507-4eb7-941d-b7680ccdeaa3

	/// This measure counts the total number of arrangements that were active during a given timeframe.
	measure '# of Arrangements Active' =
			
			VAR Today = TODAY()
			VAR CurrentStartDate = [Selected Timeframe Start]
			VAR CurrentEndDate = MIN(Today, [Selected Timeframe End])
			RETURN
			IF(
			    CurrentStartDate > Today,  // Check if the current month's start is beyond today
			    BLANK(),  // Return blank for future months
			    CALCULATE(
			        COUNTROWS('Arrangement'),
			        NOT ISBLANK('Arrangement'[Started]),
			        'Arrangement'[Started] <= CurrentEndDate,
			        IF(
			            ISBLANK('Arrangement'[Ended]),
			            TRUE(),
			            'Arrangement'[Ended] >= CurrentStartDate
			        )
			    )
			)
		formatString: 0
		lineageTag: b5357dbe-d3a2-46be-88ea-51a81a4f7727

		changedProperty = IsHidden

	/// This measure counts the total number of arrangements that were started during a given timeframe.
	measure '# of Arrangements Started' =
			
			CALCULATE(
			    COUNTROWS(Arrangement),
			    FILTER(
			        Arrangement,
			        AND(
			            Arrangement[Started] >= [Selected Timeframe Start],
			            Arrangement[Started] <= [Selected Timeframe End]
			        )
			    )
			)
		formatString: 0
		lineageTag: fae25eef-8ecc-485d-8834-68702ea83c10

		changedProperty = IsHidden

	/// This measure counts the total number of arrangements that were requested during a given timeframe (including potential duplicates that were later canceled).
	measure '# of Arrangements Requested' =
			
			CALCULATE(
			    COUNTROWS(Arrangement),
			    FILTER(
			        Arrangement,
			        AND(
			            Arrangement[Requested] >= [Selected Timeframe Start],
			            Arrangement[Requested] <= [Selected Timeframe End]
			        )
			    )
			)
		formatString: 0
		lineageTag: 7745e4b8-b452-4620-9400-d7f472736ce3

	measure '# of Days Active in Period' =
			
			VAR TimePeriodStart = MIN('Date'[Date])
			VAR TimePeriodEnd = MAX('Date'[Date])
			RETURN
			    CALCULATE(
			        SUMX(
			            'Arrangement',
			            VAR StartDate = 'Arrangement'[Started]
			            VAR EndDate = IF (ISBLANK('Arrangement'[Ended]), UTCNOW(), 'Arrangement'[Ended])
			            VAR DurationInDays = DATEDIFF(StartDate, EndDate, DAY)
			            RETURN
			                IF (StartDate >= TimePeriodStart && EndDate <= TimePeriodEnd,
			                    DurationInDays,
			                    IF (StartDate < TimePeriodStart && EndDate <= TimePeriodEnd,
			                        DATEDIFF(TimePeriodStart, EndDate, DAY),
			                        IF (StartDate >= TimePeriodStart && EndDate > TimePeriodEnd,
			                            DATEDIFF(StartDate, TimePeriodEnd, DAY),
			                            DATEDIFF(TimePeriodStart, TimePeriodEnd, DAY)
			                        )
			                    )
			                ) + 1
			        ),
			        AND(
			            NOT(ISBLANK(Arrangement[Started])),
			            AND(
			                'Arrangement'[Started] <= TimePeriodEnd,
			                OR(ISBLANK('Arrangement'[Ended]), 'Arrangement'[Ended] >= TimePeriodStart)
			            )
			        )
			    )
		formatString: 0
		isHidden
		lineageTag: fa20e53e-8d7f-411d-857e-04019308dd65

		changedProperty = IsHidden

	/// This measure counts the total number of arrangements that were ended during a given timeframe.
	measure '# of Arrangements Ended' =
			
			CALCULATE(
			    COUNTROWS(Arrangement),
			    FILTER(
			        Arrangement,
			        AND(
			            Arrangement[Ended] >= [Selected Timeframe Start],
			            Arrangement[Ended] <= [Selected Timeframe End]
			        )
			    )
			)
		formatString: 0
		lineageTag: e7a87195-5fed-473e-8658-94bce5098c3c

	measure '# of Arrangements' = COUNTROWS(Arrangement)
		formatString: 0
		lineageTag: 381d4567-b699-4dbf-b701-ef0c6febcd07

	measure 'Total Arrangements Duration' = ```
			
			// Mean length of arrangement in days, based on arrangement start/end date
			
			VAR Today = TODAY()
			VAR CurrentStartDate = [Selected Timeframe Start]
			VAR CurrentEndDate = MIN(Today, [Selected Timeframe End])
			
			RETURN IF(
			    CurrentStartDate > Today, 
			    BLANK(),
			    SUMX(
			        FILTER(
			            Arrangement,
			            NOT ISBLANK(Arrangement[Started]) &&
			            Arrangement[Started] <= CurrentEndDate &&
			            IF(
			                ISBLANK('Arrangement'[Ended]),
			                TRUE(),
			                'Arrangement'[Ended] >= CurrentStartDate
			            )
			        ),
			        DATEDIFF(
			            Arrangement[Started], Arrangement[Ended], DAY
			        )
			    )
			)
			```
		formatString: #,0
		lineageTag: f9a31601-b76f-4852-b47d-5e05f23f4131

	measure 'Average Arrangements Duration' = ```
			
			// Average duration of arrangements in days, based on arrangement start/end date
			
			VAR Today = TODAY()
			VAR CurrentStartDate = [Selected Timeframe Start]
			VAR CurrentEndDate = MIN(Today, [Selected Timeframe End])
			
			RETURN IF(
			    CurrentStartDate > Today, 
			    BLANK(),
			    AVERAGEX(
			        FILTER(
			            Arrangement,
			            NOT ISBLANK(Arrangement[Started]) &&
			            Arrangement[Started] <= CurrentEndDate &&
			            IF(
			                ISBLANK('Arrangement'[Ended]),
			                TRUE(),
			                'Arrangement'[Ended] >= CurrentStartDate
			            )
			        ),
			        DATEDIFF(
			            Arrangement[Started], Arrangement[Ended], DAY
			        )
			    )
			)
			```
		formatString: 0
		lineageTag: 81bee6c3-a2f4-4f86-ae58-d85cfd49bc5e

	column Id
		dataType: string
		isKey
		displayFolder: _Columns
		lineageTag: f2b5e1bb-5f70-4a51-ae2d-224a87725b61
		summarizeBy: none
		sourceColumn: Id

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column ReferralId
		dataType: string
		isHidden
		displayFolder: _Columns
		lineageTag: c2ba4d85-eb62-48a9-9d35-f7ec94997aef
		summarizeBy: none
		sourceColumn: ReferralId

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column PersonId
		dataType: string
		displayFolder: _Columns
		lineageTag: ef5bf3c2-4ea1-459b-9d35-1f632e10e5ad
		summarizeBy: none
		sourceColumn: PersonId

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Started
		dataType: dateTime
		formatString: General Date
		displayFolder: _Columns
		lineageTag: c2f7a97c-28a4-4ca3-aaf2-795d8a72a5f1
		summarizeBy: none
		sourceColumn: Started

		variation Variation
			isDefault
			relationship: bb43cb93-5366-4c83-85f8-417eb76a0ee4
			defaultHierarchy: LocalDateTable_24602e63-6fc7-4520-a5af-36f3df0426a8.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column Ended
		dataType: dateTime
		formatString: General Date
		displayFolder: _Columns
		lineageTag: 2450bd4a-7cef-4f62-a39c-97a1705bb84c
		summarizeBy: none
		sourceColumn: Ended

		variation Variation
			isDefault
			relationship: f6af9189-e041-4e8e-a848-1bb59b7f3b98
			defaultHierarchy: LocalDateTable_f42c1403-e66d-4045-8af6-5c3c28e884e6.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column Phase
		dataType: string
		isHidden
		displayFolder: _Columns
		lineageTag: e3591ad9-309c-4413-9fd5-93604a1e56f7
		summarizeBy: none
		sourceColumn: Phase

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Requested
		dataType: dateTime
		formatString: Long Date
		displayFolder: _Columns
		lineageTag: 855218dc-5a64-443f-af71-d76b1c4f4bd7
		summarizeBy: none
		sourceColumn: Requested

		variation Variation
			isDefault
			relationship: 7d4f3e4a-8e5e-49d7-9b0b-ca9ed9f0051f
			defaultHierarchy: LocalDateTable_73d01070-72e6-4583-b4ff-d5fa05eb2eee.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column TypeName
		dataType: string
		displayFolder: _Columns
		lineageTag: 7b953b76-e099-42ba-a699-324bd31c0a51
		summarizeBy: none
		sourceColumn: TypeName

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Days in Setup' =
			
			VAR DaysInSetup = IF(
			    ISBLANK(Arrangement[Requested]),
			    BLANK(),
			    DATEDIFF(
			        Arrangement[Requested],
			        IF(
			            ISBLANK(Arrangement[Started]),
			            UTCNOW(),
			            Arrangement[Started]),
			            DAY))
			RETURN IF(
			    DaysInSetup < 0,
			    BLANK(),
			    DaysInSetup)
		formatString: 0
		displayFolder: _Columns
		lineageTag: 9691cebc-751d-4afa-94d8-b631599de770
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column 'Days Active' =
			
			VAR DaysActive = IF(
			    ISBLANK(Arrangement[Started]),
			    BLANK(),
			    DATEDIFF(
			        Arrangement[Started],
			        IF(
			            ISBLANK(Arrangement[Ended]),
			            UTCNOW(),
			            Arrangement[Ended]),
			            DAY))
			RETURN IF(
			    DaysActive < 0,
			    BLANK(),
			    DaysActive)
		formatString: 0
		displayFolder: _Columns
		lineageTag: 6d28faa9-7da1-4ebd-96d0-a246320f0a50
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column 'Person Age at Start' = DATEDIFF(RELATED(Entity[DateOfBirth]), Arrangement[Started], YEAR)
		formatString: 0
		displayFolder: _Columns
		lineageTag: 9b8d247f-6a51-4d0f-9e31-b96930045f38
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column Reason
		dataType: string
		displayFolder: _Columns
		lineageTag: 9af6d5a9-c29d-4b9e-8110-27192afcd2d6
		summarizeBy: none
		sourceColumn: Reason

		annotation SummarizationSetBy = Automatic

	column 'Full Name' = RELATED(Entity[Full Name])
		displayFolder: _Columns
		lineageTag: 797e3615-7225-4637-a685-de0b142b6384
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column OrganizationId
		dataType: string
		lineageTag: 1668d02e-d11c-42c3-bf18-78116bfd49c6
		summarizeBy: none
		sourceColumn: OrganizationId

		annotation SummarizationSetBy = Automatic

	column LocationId
		dataType: string
		lineageTag: 396386fc-67de-4da1-888e-a12ff95ad6c6
		summarizeBy: none
		sourceColumn: LocationId

		annotation SummarizationSetBy = Automatic

	partition Arrangement-29b16dc9-0b71-4817-97ff-82d89d8e0d95 = m
		mode: import
		queryGroup: 'Model Queries'
		source =
				let
				    Source = #"OData Live",
				    Arrangement_table = Source{[Name="Arrangement",Signature="table"]}[Data],
				    #"Removed Columns" = Table.RemoveColumns(Arrangement_table,{"Referral", "Person", "Type", "OrganizationId", "LocationId"}),
				    #"Calculated Local Time" = Table.TransformColumns(#"Removed Columns",{{"StartedUtc", DateTimeZone.ToLocal, type datetimezone}, {"EndedUtc", DateTimeZone.ToLocal, type datetimezone}}),
				    #"Renamed Columns" = Table.RenameColumns(#"Calculated Local Time",{{"StartedUtc", "Started"}, {"EndedUtc", "Ended"}}),
				    #"Expanded Organization" = Table.ExpandRecordColumn(#"Renamed Columns", "Organization", {"Id"}, {"Organization.Id"}),
				    #"Expanded Location" = Table.ExpandRecordColumn(#"Expanded Organization", "Location", {"Id"}, {"Location.Id"}),
				    #"Renamed Columns1" = Table.RenameColumns(#"Expanded Location",{{"Organization.Id", "OrganizationId"}, {"Location.Id", "LocationId"}})
				in
				    #"Renamed Columns1"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

