table 'Arrangement Type'
	lineageTag: b2303fb3-bd33-4a97-9b0d-831a6ca8cf94

	column 'RLS Key'
		dataType: string
		lineageTag: 4d907de0-fdbb-4b8d-940c-a9176ccd63f7
		summarizeBy: none
		sourceColumn: RLS Key

		annotation SummarizationSetBy = Automatic

	column 'Arrangement Type'
		dataType: string
		lineageTag: 8bdc2303-5798-400a-9fca-8ce0c988015c
		summarizeBy: none
		sourceColumn: Arrangement Type

		annotation SummarizationSetBy = Automatic

	column 'Arrangement Type UID'
		dataType: string
		lineageTag: 277471fe-0821-4d8b-bea7-abc26c33fa1d
		summarizeBy: none
		sourceColumn: Arrangement Type UID

		annotation SummarizationSetBy = Automatic

	column 'Child Involvement'
		dataType: string
		lineageTag: 0ec739bb-7ad6-4b96-b664-224ef7a2ae91
		summarizeBy: none
		sourceColumn: Child Involvement

		annotation SummarizationSetBy = Automatic

	partition 'Arrangement Type' = m
		mode: import
		queryGroup: Dimensions
		source = ```
				let
				    Source = #"OData Live",
				    ArrangementType = Source{[Name="ArrangementType", Signature="table"]}[Data],
				
				    ArrangementTypeTransformed = 
				    
				Table.SelectColumns(
				    Table.RenameColumns(
				        Table.AddColumn(
				            Table.AddColumn(
				                ArrangementType,
				                "RLS Key", each Text.Combine({[OrganizationId], [LocationId]}, "-")
				            ),
				            "Arrangement Type UID", each Text.Combine({[RLS Key], [Type]}, "-")
				        ),
				        {{"Type", "Arrangement Type"}, {"ChildInvolvement", "Child Involvement"}}
				    ),
				    {"RLS Key", "Arrangement Type UID", "Arrangement Type", "Child Involvement"}
				
				)
				
				
				in
				    ArrangementTypeTransformed
				```

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

