table 'Arrangement Phase'
	lineageTag: 8a45b6de-6ddf-451f-885a-53d149374a7d

	column ArrangementPhase
		dataType: string
		isHidden
		isKey
		lineageTag: 1e1d52e5-44c2-42df-ab7b-cda676950d8a
		summarizeBy: none
		sourceColumn: ArrangementPhase
		sortByColumn: Order

		changedProperty = IsHidden

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column Order
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 1affe2e0-9a6a-42ae-ad9c-4adf00b8e88c
		summarizeBy: none
		sourceColumn: Order

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Phase
		dataType: string
		lineageTag: e3c0590f-b1f2-4fcb-a8d0-5d3b65d8135a
		isDefaultLabel
		summarizeBy: none
		sourceColumn: Phase
		sortByColumn: Order

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	partition 'Arrangement Phase-adc369f2-fbe6-4739-b999-19b921f01eb8' = m
		mode: import
		queryGroup: 'Reference Tables'
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i45WCk4tKcnMSw8tUNJRMgBiKF8BKBCrE60UlJqYUhmSH1ySWFQClDUEYrCQQkm+AkQQpArMSk0BShqBjIDyQDKueSlgcWMghrBBos6JecmpOTlgGRMgRvBjYwE=", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [ArrangementPhase = _t, Order = _t, Phase = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"ArrangementPhase", type text}, {"Order", Int64.Type}, {"Phase", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

