table 'Arrangement Type'
	lineageTag: c7cb613d-9d95-4212-99b0-afeb17ed7411

	column 'Arrangement Type'
		dataType: string
		isKey
		lineageTag: 6d868529-a926-4987-abe4-9cb21a750b7e
		isDefaultLabel
		summarizeBy: none
		sourceColumn: Arrangement Type

		annotation SummarizationSetBy = Automatic

	column ChildInvolvement
		dataType: string
		isHidden
		lineageTag: 106f4bcb-6fa8-4ebc-a504-f2cad0bf9090
		summarizeBy: none
		sourceColumn: ChildInvolvement

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column OrganizationId
		dataType: string
		lineageTag: 5cedf8f1-dd7b-4e63-a0af-d8a544bd21b2
		summarizeBy: none
		sourceColumn: OrganizationId

		annotation SummarizationSetBy = Automatic

	column LocationId
		dataType: string
		lineageTag: 9e5ea841-b6d3-4c17-bfa3-0e20de93dd3c
		summarizeBy: none
		sourceColumn: LocationId

		annotation SummarizationSetBy = Automatic

	partition 'Arrangement Type-597c3ca7-59e2-4e86-8453-c8def7291a36' = m
		mode: import
		queryGroup: 'Model Queries'
		source =
				let
				    Source = #"OData Live",
				    ArrangementType_table1 = Source{[Name="ArrangementType",Signature="table"]}[Data],
				    #"Removed Columns" = Table.RemoveColumns(ArrangementType_table1,{"OrganizationId", "LocationId"}),
				    #"Expanded Organization" = Table.ExpandRecordColumn(#"Removed Columns", "Organization", {"Id"}, {"Organization.Id"}),
				    #"Expanded Location" = Table.ExpandRecordColumn(#"Expanded Organization", "Location", {"Id"}, {"Location.Id"}),
				    #"Renamed Columns" = Table.RenameColumns(#"Expanded Location",{{"Type", "Arrangement Type"}, {"Organization.Id", "OrganizationId"}, {"Location.Id", "LocationId"}})
				in
				    #"Renamed Columns"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

