table 'Arrangement Type'
	lineageTag: c7cb613d-9d95-4212-99b0-afeb17ed7411

	column 'RLS Key'
		dataType: string
		lineageTag: d5779dd9-d981-42f6-a99f-94f9a0b4660d
		summarizeBy: none
		sourceColumn: RLS Key

		annotation SummarizationSetBy = Automatic

	column 'Arrangement Type'
		dataType: string
		lineageTag: 43965f59-42d2-47e8-ba87-6943e599d63a
		summarizeBy: none
		sourceColumn: Arrangement Type

		annotation SummarizationSetBy = Automatic

	column ChildInvolvement
		dataType: string
		isHidden
		lineageTag: 106f4bcb-6fa8-4ebc-a504-f2cad0bf9090
		summarizeBy: none
		sourceColumn: ChildInvolvement

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Arrangement Type PK'
		dataType: string
		lineageTag: ca1384fb-2f66-48e5-8dea-b8c9c7fbb685
		summarizeBy: none
		sourceColumn: Arrangement Type PK

		annotation SummarizationSetBy = Automatic

	partition 'Arrangement Type-597c3ca7-59e2-4e86-8453-c8def7291a36' = m
		mode: import
		queryGroup: 'Model Queries'
		source = ```
				let
				    Source = #"OData Live",
				    SourceTable = Source{[Name="ArrangementType",Signature="table"]}[Data],
				
				    ArrangementType = 
				    Table.SelectColumns(
				        Table.AddColumn(
				            Table.AddColumn(
				                Table.RenameColumns(
				                    SourceTable,
				                    {{"Type", "Arrangement Type"}}
				                ),
				                "RLS Key", each Text.Combine({[OrganizationId], [LocationId]}, "-")
				            ),
				        "Arrangement Type PK", each Text.Combine({[RLS Key], [Arrangement Type]}, "-")
				        ),
				        {"RLS Key", "Arrangement Type PK", "Arrangement Type", "ChildInvolvement"}
				    )
				in
				    ArrangementType
				```

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

