table Cases
	lineageTag: 9e3a875e-349f-43da-84eb-8c636fdefbc9

	measure '# of Cases Opened' =
			COUNTROWS(
			    FILTER(
			        'Cases',
			        AND(
			            'Cases'[Opened] >= [Selected Timeframe Start],
			            'Cases'[Opened] <= [Selected Timeframe End]
			        )
			    )
			)
		formatString: 0
		lineageTag: f3c404d6-390c-431b-9b69-8eb6b0e63a25

	column 'RLS Key'
		dataType: string
		displayFolder: _Columns
		lineageTag: cd5525dd-e937-49df-b204-6c81e4fda7f7
		summarizeBy: none
		sourceColumn: RLS Key

		annotation SummarizationSetBy = Automatic

	column 'Family UID'
		dataType: string
		displayFolder: _Columns
		lineageTag: 738b7dad-745e-4b9d-abf1-6e9042b82ab7
		summarizeBy: none
		sourceColumn: Family UID

		annotation SummarizationSetBy = Automatic

	column 'Family ID'
		dataType: string
		displayFolder: _Columns
		lineageTag: 324a14fb-9785-443c-9b0f-17c8e2cdfd72
		summarizeBy: none
		sourceColumn: Family ID

		annotation SummarizationSetBy = Automatic

	column Opened
		dataType: dateTime
		formatString: Short Date
		displayFolder: _Columns
		lineageTag: 3735aae9-a05e-45e2-b675-64e5b18b46bc
		summarizeBy: none
		sourceColumn: Opened

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Closed
		dataType: dateTime
		formatString: Short Date
		displayFolder: _Columns
		lineageTag: 731a711a-6cf1-4553-98be-25be1f1b4b11
		summarizeBy: none
		sourceColumn: Closed

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Referral Source'
		dataType: string
		displayFolder: _Columns
		lineageTag: 9ec71218-11b8-4ae6-a43b-42a01cbbef9b
		summarizeBy: none
		sourceColumn: Referral Source

		annotation SummarizationSetBy = Automatic

	column 'Close Reason'
		dataType: string
		displayFolder: _Columns
		lineageTag: ac057b4d-f637-493e-ad3e-e4d72feb95da
		summarizeBy: none
		sourceColumn: Close Reason

		annotation SummarizationSetBy = Automatic

	column 'Primary Reason for Referral'
		dataType: string
		displayFolder: _Columns
		lineageTag: ae7e18ff-b6f6-4a22-aa8b-8389894dd252
		summarizeBy: none
		sourceColumn: Primary Reason for Referral

		annotation SummarizationSetBy = Automatic

	column 'Case UID'
		dataType: string
		lineageTag: 2305de83-d39e-4ac5-8ddc-bb33ec91c717
		summarizeBy: none
		sourceColumn: Case UID

		annotation SummarizationSetBy = Automatic

	partition Cases = m
		mode: import
		queryGroup: Fact
		source = ```
				let
				    Source = #"OData Live",
				    Referral = Source{[Name="Cases", Signature="table"]}[Data],
				    ReferralTransformed = 
				
				    Table.SelectColumns(
				        Table.RenameColumns(
				            Table.AddColumn(
				                Table.AddColumn(
				                    Table.AddColumn(
				                        Referral,
				                        "RLS Key", each Text.Combine({[OrganizationId], [LocationId]}, "-")
				                    ),
				                    "Family UID", each Text.Combine({[RLS Key], [FamilyId]}, "-")
				                ),
				                "Case UID", each Text.Combine({[RLS Key], [CaseId]}, "-")
				            ),
				            {{"CaseId", "Case ID"}, {"FamilyId", "Family ID"}, {"ReferralSource", "Referral Source"}, {"CloseReason", "Close Reason"}, {"PrimaryReasonForReferral", "Primary Reason for Referral"}}
				        ),
				        {"RLS Key", "Case UID", "Family UID", "Family ID", "Opened", "Closed", "Referral Source", "Close Reason", "Primary Reason for Referral"}
				    )
				
				
				
				
				in
				    ReferralTransformed
				```

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

