table Childcare
	lineageTag: 0e929471-7d25-410a-953a-359fbad618e6

	column ChildInvolvement
		dataType: string
		lineageTag: 2e7eee7b-f723-4a38-bf92-87b7accdd83f
		summarizeBy: none
		sourceColumn: ChildInvolvement

		annotation SummarizationSetBy = Automatic

	column Order
		dataType: int64
		formatString: 0
		lineageTag: 86c56b6e-4c46-4244-98ca-1a62fc061ec1
		summarizeBy: none
		sourceColumn: Order

		annotation SummarizationSetBy = Automatic

	column 'Care Type'
		dataType: string
		lineageTag: c2f8c83b-0e63-4e75-8edc-b90a683a7e39
		summarizeBy: none
		sourceColumn: Care Type

		annotation SummarizationSetBy = Automatic

	partition Childcare = m
		mode: import
		queryGroup: Dimensions
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i45Wcs7IzEnxyC8tzsxLV9JRMgBisJACTCxWJ1rJJbGyJDM3FSzhnFiU6p+XUwlUaAjEUCkFsFwyUE4BLAnS5ZcPFvTMK8vPKUvNTc0rAao3AmK/fIhyBWSp2FgA", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [ChildInvolvement = _t, Order = _t, Involvement = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"ChildInvolvement", type text}, {"Order", Int64.Type}, {"Involvement", type text}}),
				    #"Renamed Columns" = Table.RenameColumns(#"Changed Type",{{"Involvement", "Care Type"}})
				in
				    #"Renamed Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

