table 'Close Reason'
	lineageTag: a1d60698-0bd2-4f71-8c12-2867d488fec6

	column ReferralCloseReason
		dataType: string
		lineageTag: 2f823fb4-8427-475f-941b-b81afdb13f93
		summarizeBy: none
		sourceColumn: ReferralCloseReason

		annotation SummarizationSetBy = Automatic

	column Order
		dataType: int64
		formatString: 0
		lineageTag: 11146fae-f535-4494-9f8f-f904ecd0e2cd
		summarizeBy: none
		sourceColumn: Order

		annotation SummarizationSetBy = Automatic

	column Reason
		dataType: string
		lineageTag: 78cc5d34-4bbf-4f5e-bea8-f1afb1ed3113
		summarizeBy: none
		sourceColumn: Reason

		annotation SummarizationSetBy = Automatic

	partition 'Close Reason' = m
		mode: import
		queryGroup: Dimensions
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("Tcw9DoAgDIbhqzTMDP5dwLgqgythINAYFiGIg7e3gFGHDt+bJ5WSCZ/GEKIP0emEjLOGjiL8q+IZTjpo49JFoC0I3lLB7PcNo0C0aAl0FdUKT85yxcOf0RTU0327/CG4YKI+5Ae0IE+lbg==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [ReferralCloseReason = _t, Order = _t, Reason = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"ReferralCloseReason", type text}, {"Order", Int64.Type}, {"Reason", type text}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

