table 'Community Role Assignments'
	lineageTag: 5d48d610-1f9d-4a9e-bae4-ef9ac4fec4a1

	column CommunityId
		dataType: string
		isHidden
		lineageTag: 8cbad8e8-1fa4-4947-9e30-e6c6d4b71dea
		summarizeBy: none
		sourceColumn: CommunityId

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column PersonId
		dataType: string
		isHidden
		lineageTag: d67b77c7-3c6e-41ae-8a71-5071b169804f
		summarizeBy: none
		sourceColumn: PersonId

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Role
		dataType: string
		lineageTag: 06599e01-9ba0-42ec-b312-72f9bcf5e226
		summarizeBy: none
		sourceColumn: Role

		annotation SummarizationSetBy = Automatic

	column 'RLS Key'
		dataType: string
		lineageTag: 7d7dc74e-96dc-4d55-b1f7-05c70051b20d
		summarizeBy: none
		sourceColumn: RLS Key

		annotation SummarizationSetBy = Automatic

	partition 'Community Role Assignments' = m
		mode: import
		queryGroup: 'Model Queries'
		source = ```
				let
				    Source = #"OData Live",
				    SourceTable = Source{[Name="CommunityRoleAssignments",Signature="table"]}[Data],
				
				    CommunityRoleAssignments = 
				
				    Table.SelectColumns(
				        Table.AddColumn(
				            SourceTable,
				            "RLS Key", each Text.Combine({[OrganizationId], [LocationId]}, "-")
				        ),
				        {"RLS Key", "CommunityId", "PersonId", "Role"}
				    )
				    
				
				in
				    CommunityRoleAssignments
				```

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

