table Community
	lineageTag: e7a84953-27c2-4818-8b9a-4ebdd0ebcb9d

	measure 'First Community Membership' =
			
			VAR FirstCommunity = MIN(Community[Community Name])
			RETURN IF(ISBLANK(FirstCommunity), "", FirstCommunity)
		lineageTag: b408252d-cb32-499f-8753-1aa99f2c2283

	measure 'ID Count' = DISTINCTCOUNT(Community[Community ID])
		formatString: 0
		lineageTag: 5606c5bf-f880-4201-bceb-96505bc09ff6

	column 'RLS Key'
		dataType: string
		displayFolder: _Columns
		lineageTag: 8f3ad27a-2280-44ba-a5e5-bcbd74e914fe
		summarizeBy: none
		sourceColumn: RLS Key

		annotation SummarizationSetBy = Automatic

	column 'Community Name'
		dataType: string
		displayFolder: _Columns
		lineageTag: 0d2c8dc8-fed8-4620-b022-4017f39e0774
		summarizeBy: none
		sourceColumn: Community Name

		annotation SummarizationSetBy = Automatic

	column 'Community ID'
		dataType: string
		displayFolder: _Columns
		lineageTag: 447eff34-66a1-4168-b2db-0e731d6511e3
		summarizeBy: none
		sourceColumn: Community ID

		annotation SummarizationSetBy = Automatic

	column 'Community UID'
		dataType: string
		lineageTag: 126b08b6-00fb-4559-8aad-b0a4527d45a0
		summarizeBy: none
		sourceColumn: Community UID

		annotation SummarizationSetBy = Automatic

	partition Community = m
		mode: import
		queryGroup: Dimensions
		source = ```
				let
				    Source = #"OData Live",
				    Community = Source{[Name="Communities", Signature="table"]}[Data],
				    CommunityTransformed = 
				
				    Table.SelectColumns(
				        Table.RenameColumns(
				            Table.AddColumn(
				                Table.AddColumn(
				                    Community,
				                    "RLS Key", each Text.Combine({[OrganizationId], [LocationId]}, "-")
				                ),
				                "Community UID", each Text.Combine({[RLS Key], [Id], "-"})
				            ),
				            {{"Id", "Community ID"}, {"Name", "Community Name"}}
				        ),
				        {"RLS Key", "Community UID", "Community ID", "Community Name"}
				    )
				in
				    CommunityTransformed
				```

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

