table 'Community Role Assignments'
	lineageTag: f609fd05-22d1-4600-8e45-7cf87904cf76

	column 'RLS Key'
		dataType: string
		lineageTag: 7bf9a5d5-ee29-4feb-b494-9072f7263506
		summarizeBy: none
		sourceColumn: RLS Key

		annotation SummarizationSetBy = Automatic

	column Role
		dataType: string
		lineageTag: c848d7ef-86c7-4d49-b2e0-86ca01633a01
		summarizeBy: none
		sourceColumn: Role

		annotation SummarizationSetBy = Automatic

	column 'Community ID'
		dataType: string
		lineageTag: 2df87865-be6e-4f30-a526-aa2b7d43d21e
		summarizeBy: none
		sourceColumn: Community ID

		annotation SummarizationSetBy = Automatic

	column 'Person UID'
		dataType: string
		lineageTag: 493fbb49-1acd-4647-af59-6f58ab32a590
		summarizeBy: none
		sourceColumn: Person UID

		annotation SummarizationSetBy = Automatic

	column 'Person ID'
		dataType: string
		lineageTag: c2cfbeea-7e85-47ba-82f8-e9dcd9c0f06a
		summarizeBy: none
		sourceColumn: Person ID

		annotation SummarizationSetBy = Automatic

	column 'Community UID'
		dataType: string
		lineageTag: d7498932-3467-4f23-9ba2-4dbefacec77b
		summarizeBy: none
		sourceColumn: Community UID

		annotation SummarizationSetBy = Automatic

	partition 'Community Role Assignments' = m
		mode: import
		queryGroup: Fact
		source = ```
				let
				    Source = #"OData Live",
				    CommunityRoleAssignment = Source{[Name="CommunityRoleAssignments", Signature="table"]}[Data],
				    
				    CommunityRoleAssignmentTransformed = 
				
				    Table.SelectColumns(
				        Table.RenameColumns(
				            Table.AddColumn(
				                Table.AddColumn(
				                    Table.AddColumn(
				                        CommunityRoleAssignment,
				                        "RLS Key", each Text.Combine({[OrganizationId], [LocationId]}, "-")
				                    ),
				                    "Person UID", each Text.Combine({[RLS Key], [PersonId]}, "-")
				                ),
				                "Community UID", each Text.Combine({[RLS Key], [CommunityId], "-"})
				            ),
				            {{"CommunityId", "Community ID"}, {"PersonId", "Person ID"}}
				        ),
				        {"RLS Key", "Community UID", "Community ID", "Person UID", "Person ID", "Role"}
				    )
				
				
				in
				    CommunityRoleAssignmentTransformed
				```

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

