table Community
	lineageTag: f38961a2-f1d1-478b-87f7-d848cfbf0304

	measure '# of Communities' = COUNTROWS(Community)
		formatString: 0
		lineageTag: 936a49f0-4f83-4056-bd40-561afd518652

	measure 'First Community Membership' =
			
			
			VAR FirstCommunity = MIN(Community[Name])
			
			RETURN IF(ISBLANK(FirstCommunity), "", FirstCommunity)
		lineageTag: b7d1d23d-01bf-4edc-ab56-d3625c342b19

	column Id
		dataType: string
		isHidden
		isKey
		lineageTag: 635a01f9-6329-4a2d-92a8-cfd868d53381
		summarizeBy: none
		sourceColumn: Id

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Name
		dataType: string
		lineageTag: 129fec00-1f2b-4369-a96b-fdc0549392fa
		isDefaultLabel
		summarizeBy: none
		sourceColumn: Name

		annotation SummarizationSetBy = Automatic

	column 'Community Membership Count' = COUNTROWS(RELATEDTABLE('Community Member Families'))
		formatString: 0
		lineageTag: 7d18a30a-e29a-424d-8374-b7e090f3ea28
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column OrganizationId
		dataType: string
		lineageTag: 10648cd9-5d83-46c5-9219-32b863a8e7db
		summarizeBy: none
		sourceColumn: OrganizationId

		annotation SummarizationSetBy = Automatic

	column LocationId
		dataType: string
		lineageTag: 977c9e84-5700-4100-8be7-ad46beb14739
		summarizeBy: none
		sourceColumn: LocationId

		annotation SummarizationSetBy = Automatic

	partition Community = m
		mode: import
		queryGroup: 'Model Queries'
		source =
				let
				    Source = #"OData Live",
				    Families_table = Source{[Name="Communities",Signature="table"]}[Data],
				    #"Expanded Organization" = Table.ExpandRecordColumn(Families_table, "Organization", {"Id"}, {"Organization.Id"}),
				    #"Expanded Location" = Table.ExpandRecordColumn(#"Expanded Organization", "Location", {"Id", "OrganizationId", "Name"}, {"Location.Id", "Location.OrganizationId", "Location.Name"}),
				    #"Removed Columns" = Table.RemoveColumns(#"Expanded Location",{"OrganizationId", "LocationId"}),
				    #"Renamed Columns" = Table.RenameColumns(#"Removed Columns",{{"Organization.Id", "OrganizationId"}, {"Location.Id", "LocationId"}}),
				    #"Removed Columns1" = Table.RemoveColumns(#"Renamed Columns",{"Location.OrganizationId", "Location.Name"})
				in
				    #"Removed Columns1"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

