table 'Community Member Families'
	lineageTag: 785f05bf-7c33-4d73-a7e1-fb1007f192e8

	column 'RLS Key'
		dataType: string
		lineageTag: 4e29f0b1-3790-41b3-9ea6-d80cd45f6914
		summarizeBy: none
		sourceColumn: RLS Key

		annotation SummarizationSetBy = Automatic

	column 'Family UID'
		dataType: string
		lineageTag: b20a44ac-0455-4d8e-91db-be4d5f63a796
		summarizeBy: none
		sourceColumn: Family UID

		annotation SummarizationSetBy = Automatic

	column 'Family ID'
		dataType: string
		lineageTag: 08d4ac8d-675d-45e4-a88a-182c0c068432
		summarizeBy: none
		sourceColumn: Family ID

		annotation SummarizationSetBy = Automatic

	column 'Community ID'
		dataType: string
		lineageTag: 0e504c9a-2416-4a78-9aeb-b4391e65b05f
		summarizeBy: none
		sourceColumn: Community ID

		annotation SummarizationSetBy = Automatic

	partition 'Community Member Families' = m
		mode: import
		queryGroup: Fact
		source = ```
				let
				    Source = #"OData Live",
				    Community = Source{[Name="CommunityMemberFamilies", Signature="table"]}[Data],
				    CommunityTransformed = 
				
				    Table.SelectColumns(
				        Table.RenameColumns(
				            Table.AddColumn(
				                Table.AddColumn(
				                    Community,
				                    "RLS Key", each Text.Combine({[OrganizationId], [LocationId]}, "-")
				                ),
				                "Family UID", each Text.Combine({[RLS Key], [FamilyId]}, "-")
				            ),
				            {{"CommunityId", "Community ID"}, {"FamilyId", "Family ID"}}
				        ),
				        {"RLS Key", "Family UID", "Family ID", "Community ID"}
				    )
				in
				    CommunityTransformed
				```

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

