table Community
	lineageTag: f38961a2-f1d1-478b-87f7-d848cfbf0304

	measure '# of Communities' = COUNTROWS(Community)
		formatString: 0
		lineageTag: 936a49f0-4f83-4056-bd40-561afd518652

	measure 'First Community Membership' =
			
			
			VAR FirstCommunity = MIN(Community[Community Name])
			
			RETURN IF(ISBLANK(FirstCommunity), "", FirstCommunity)
		lineageTag: b7d1d23d-01bf-4edc-ab56-d3625c342b19

	column Id
		dataType: string
		isHidden
		isKey
		lineageTag: 635a01f9-6329-4a2d-92a8-cfd868d53381
		summarizeBy: none
		sourceColumn: Id

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column LocationId
		dataType: string
		isHidden
		lineageTag: 0cfac6c8-71df-440e-b16d-b9c44f18615f
		summarizeBy: none
		sourceColumn: LocationId

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Community Name'
		dataType: string
		lineageTag: 129fec00-1f2b-4369-a96b-fdc0549392fa
		isDefaultLabel
		summarizeBy: none
		sourceColumn: Community Name

		annotation SummarizationSetBy = Automatic

	column 'Community Membership Count' = COUNTROWS(RELATEDTABLE('Community Member Families'))
		formatString: 0
		lineageTag: 7d18a30a-e29a-424d-8374-b7e090f3ea28
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	partition Community = m
		mode: import
		queryGroup: 'Model Queries'
		source =
				let
				    Source = #"OData Live",
				    Families_table = Source{[Name="Communities",Signature="table"]}[Data],
				    #"Removed Columns" = Table.RemoveColumns(Families_table,{"Location"}),
				    #"Renamed Columns" = Table.RenameColumns(#"Removed Columns",{{"Name", "Community Name"}})
				in
				    #"Renamed Columns"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

