table 'Engagement by Entity'
	lineageTag: 8f2409f8-8bb7-409d-a99d-42d2502e2ec7

	calculationGroup
		precedence: 1

		calculationItem Family =
				CALCULATE (
				    SELECTEDMEASURE (),
				        USERELATIONSHIP(Entity[FamilyId], 'Function Assignments'[EntityId]),
				        CROSSFILTER(Entity[PersonId], Arrangement[PersonId], None),
				        'Role Approval'[Entity Type] = "Family",
				        USERELATIONSHIP ( Entity[FamilyId], 'Role Approval'[Entity Id] ),
				        CROSSFILTER ( Entity[PersonId], 'Role Approval'[Entity Id], NONE )
				)

		calculationItem Person =
				CALCULATE(
				    SELECTEDMEASURE (),
				    USERELATIONSHIP(Entity[PersonId], 'Function Assignments'[EntityId]),
				    CROSSFILTER(Entity[PersonId], Arrangement[PersonId], None),
				    'Role Approval'[Entity Type] = "Person",
				    USERELATIONSHIP(Entity[PersonId], 'Role Approval'[Entity Id]),
				    CROSSFILTER (Entity[FamilyId], 'Role Approval'[Entity Id], NONE)
				)

	measure 'Dynamic Entity Name (Engagement)' =
			CALCULATE(
			    SWITCH(
			        SELECTEDVALUE('Engagement by Entity'[Entity Type]),
			        "Family", CALCULATE(
			            SELECTEDVALUE(Entity[Family Name]),
			            CROSSFILTER(Entity[FamilyId], 'Role Approval'[Entity Id], Both)),
			        "Person", SELECTEDVALUE(Entity[Full Name])
			)
			)
		lineageTag: 0cd7cfa7-2eea-44a1-bde0-e6805c0adaa6

	measure '# Engaged Entities (Dynamic Title)' =
			SWITCH(
			        SELECTEDVALUE('Engagement by Entity'[Entity Type]),
			        "Family", "# of Engaged Families",
			        "Person", "# of Engaged Person"
			)
		lineageTag: f0636ec2-84be-47f6-a307-681805ad34e6

	measure '# Approved Entities (Dynamic Title)' =
			SWITCH(
			        SELECTEDVALUE('Engagement by Entity'[Entity Type]),
			        "Family", "# of Approved Families",
			        "Person", "# of Approved Person"
			)
		lineageTag: 7362fe37-2086-4c48-8aec-69f842015f5e

	column 'Entity Type'
		dataType: string
		lineageTag: 41bce2c0-a1e4-461b-9226-f9530288cc87
		summarizeBy: none
		sourceColumn: Name
		sortByColumn: Ordinal

		annotation SummarizationSetBy = Automatic

	column Ordinal
		dataType: int64
		isHidden
		lineageTag: 5dfee282-9213-400e-9f81-444b5f5c7b1a
		summarizeBy: sum
		sourceColumn: Ordinal

		annotation SummarizationSetBy = Automatic

