table Entity
	lineageTag: 18ba4465-a9c2-415f-8e79-fd884584fded

	/// Families are supported when they have an active arrangement during a given timeframe.
	measure '# of Families Supported' =
			
			
			VAR Today = TODAY()
			VAR CurrentStartDate = [Selected Timeframe Start]
			VAR CurrentEndDate = MIN(Today, [Selected Timeframe End])
			RETURN
			IF(
			    CurrentStartDate > Today,  // Check if the current month's start is beyond today
			    BLANK(),  // Return blank for future months
			    COUNTROWS(
			        FILTER(
			            VALUES(Entity[FamilyId]),
			            COUNTROWS(
			                FILTER(
			                    RELATEDTABLE('Arrangement'),
			                    NOT(ISBLANK('Arrangement'[Started])) &&
			                    'Arrangement'[Started] <= CurrentEndDate &&
			                    (
			                        ISBLANK('Arrangement'[Ended]) ||
			                        'Arrangement'[Ended] >= CurrentStartDate
			                    )
			                )
			            ) > 0
			        )
			    )
			)
		formatString: 0
		lineageTag: 42791fd1-d8d3-4e90-b404-9e4f72530deb

	/// Children are cared for when they have a location record with someone other than a parent in a given timeframe.
	measure '# of Children Cared For' = ```
			
			
			VAR CurrentDate = TODAY()
			VAR StartDate = [Selected Timeframe Start]  // This is a measure calculating the start of the desired timeframe.
			VAR EndDate = [Selected Timeframe End]  // This is a measure calculating the end of the desired timeframe.
			VAR Result =
			    CALCULATE(
			        DISTINCTCOUNTNOBLANK(Entity[PersonId]),
			        Entity[PersonType] = "Child",
			        USERELATIONSHIP(Entity[PersonId], Arrangement[PersonId]),
			        FILTER(
			            'Child Location Record',
			            'Child Location Record'[ChildcarePlan] <> "WithParent" && 
			            'Child Location Record'[Started] >= StartDate && 
			            'Child Location Record'[Started] <= MIN(EndDate, CurrentDate)
			        )
			    )
			RETURN
			    IF(
			        CurrentDate < StartDate,
			        BLANK(),
			        IF(
			            Result = 0,
			            0,
			            Result
			        )
			    )
			```
		formatString: 0
		lineageTag: f5368366-cd4e-48c5-aaad-03444bd01031

	measure '# Impacted Adults' = ```
			
			VAR Today = TODAY()
			VAR CurrentStartDate = [Selected Timeframe Start]
			VAR CurrentEndDate = MIN(Today, [Selected Timeframe End])
			
			RETURN
			IF(
			    CurrentStartDate > Today, 
			    BLANK(),
			    CALCULATE(
			        DISTINCTCOUNT(Entity[PersonId]),
			        FILTER(
			            VALUES(Entity[FamilyId]),
			            COUNTROWS(
			                FILTER(
			                    RELATEDTABLE('Arrangement'), // Added the related table to ensure that the formula correctly filters the arrangement table.
			                    NOT(ISBLANK('Arrangement'[Started])) &&
			                    'Arrangement'[Started] <= CurrentEndDate &&
			                    (
			                        ISBLANK('Arrangement'[Ended]) || 
			                        'Arrangement'[Ended] >= CurrentStartDate
			                    )
			                )
			            ) > 0
			        ),
			        Entity[PersonType] = "Adult"
			    )
			)
			```
		formatString: 0
		lineageTag: 1261a671-95aa-4b55-a006-80edcd6f411d

	measure '# Impacted Children' = ```
			
			VAR Today = TODAY()
			VAR CurrentStartDate = [Selected Timeframe Start]
			VAR CurrentEndDate = MIN(Today, [Selected Timeframe End])
			
			RETURN
			IF(
			    CurrentStartDate > Today, 
			    BLANK(),
			    CALCULATE(
			        DISTINCTCOUNT(Entity[PersonId]),
			        FILTER(
			            VALUES(Entity[FamilyId]),
			            COUNTROWS(
			                FILTER(
			                    RELATEDTABLE('Arrangement'), // Added the related table to ensure that the formula correctly filters the arrangement table.
			                    NOT(ISBLANK('Arrangement'[Started])) &&
			                    'Arrangement'[Started] <= CurrentEndDate &&
			                    (
			                        ISBLANK('Arrangement'[Ended]) || 
			                        'Arrangement'[Ended] >= CurrentStartDate
			                    )
			                )
			            ) > 0
			        ),
			        Entity[PersonType] = "Child"
			    )
			)
			```
		formatString: 0
		lineageTag: 56b2562e-e953-4c65-b7b0-d70a8a272259

	measure '# of People in Role' =
			
			VAR PeopleApprovals = CALCULATE(
			    DISTINCTCOUNT('Role Approval'[Entity Id]),
			    'Role Approval'[Entity Type] = "Person"
			)
			
			RETURN PeopleApprovals
		formatString: 0
		lineageTag: d7b95e5a-edc1-4688-8c75-5e3d08118b20

	measure '# of Approval Statuses' = ```
			CALCULATE(
			    COUNTROWS('Role Approval'),
			    'Role Approval'[Approval Type] = "Direct")
			
			```
		formatString: 0
		isHidden
		lineageTag: 202d8b72-a7a6-4280-94a4-a673b34efa25

		changedProperty = IsHidden

	measure '# of Families' = ```
			DISTINCTCOUNT(Entity[FamilyId])
			    
			```
		formatString: 0
		isHidden
		lineageTag: 982e7e0c-55e9-485e-8813-4e519005eb6f

		changedProperty = IsHidden

	measure 'Community Membership Count' = COALESCE(COUNTROWS(RELATEDTABLE('Community Member Families')),0)
		formatString: 0
		lineageTag: eab89055-f3d3-49a0-b310-ecc71d6f052c

	measure '# of People in Role (Direct Only)' =
			CALCULATE(
			    DISTINCTCOUNT('Role Approval'[Entity Id]),
			    'Role Approval'[Entity Type] = "Person",
			    'Role Approval'[Approval Type] = "Direct")
		formatString: 0
		lineageTag: 5bfeb8dc-7346-4162-a6cf-76b9b85adb13

		changedProperty = IsHidden

	measure '# of Entities in Role' = DISTINCTCOUNT('Role Approval'[Entity Id])
		formatString: 0
		lineageTag: dcc5efbd-9875-442e-a4de-2f9045a3d814

	measure 'Entity Engagement Level' =
			
			
			VAR Today = TODAY()
			VAR CurrentStartDate = [Selected Timeframe Start]
			VAR CurrentEndDate = MIN(Today, [Selected Timeframe End])
			
			RETURN
			IF(
			    CurrentStartDate > Today,
			    BLANK(),
			    CALCULATE(
			        COUNTROWS('Function Assignments'),
			        NOT ISBLANK(Arrangement[Started]),
			        Arrangement[Started] <= CurrentEndDate,
			        IF(
			            ISBLANK(Arrangement[Ended]),
			            TRUE(),
			            'Arrangement'[Ended] >= CurrentStartDate
			        )
			    )
			)
		formatString: 0
		lineageTag: ef04b2c7-710f-4f7d-ae0e-dc217a08a5ce

	measure '# of Engaged Entities' =
			
			IF(
			    SELECTEDVALUE('Engagement by Entity'[Entity Type]) = "Person",
			    CALCULATE(
			    DISTINCTCOUNT(Entity[PersonId]),
			    FILTER(
			        Entity,
			        [Entity Engagement Level] > 0
			    )),
			IF(
			    SELECTEDVALUE('Engagement by Entity'[Entity Type]) = "Family",
			    CALCULATE(
			    DISTINCTCOUNT(Entity[FamilyId]),
			    FILTER(
			        Entity,
			        [Entity Engagement Level] > 0
			    ))
			))
		formatString: 0
		lineageTag: bca680a4-55ac-4c55-a442-6aa30c0c0db0

	measure '# of Approved Entities' =
			
			VAR ApprovedFamilies = DISTINCTCOUNT('Role Approval'[Entity Id]) // All the logic for this field is defined in the Engagement calculation Group.
			VAR ApprovedPerson = CALCULATE(
			    DISTINCTCOUNT('Role Approval'[Entity Id]),
			    'Role Approval'[Approval Type] = "Direct")
			RETURN IF(SELECTEDVALUE('Engagement by Entity'[Entity Type]) = "Family", ApprovedFamilies, ApprovedPerson)
		formatString: 0
		lineageTag: 0fda565c-40bf-4267-937f-17b46f11526c

	measure 'Entity Last Assignment Date' =
			
			
			VAR Today = TODAY()
			VAR CurrentStartDate = [Selected Timeframe Start]
			VAR CurrentEndDate = MIN(Today, [Selected Timeframe End])
			
			RETURN IF(SELECTEDVALUE('Engagement by Entity'[Entity Type]) = "Family",
			
			    IF(
			        CurrentStartDate > Today,
			        BLANK(),
			        CALCULATE(
			            MAXX(
			                ADDCOLUMNS(
			                    'Function Assignments',
			                    "EffectiveEnded", IF(ISBLANK(RELATED('Arrangement'[Ended])), Today, RELATED('Arrangement'[Ended]))
			                ),
			                [EffectiveEnded]
			            ),
			            NOT ISBLANK(Arrangement[Started]),
			            Arrangement[Started] <= CurrentEndDate,
			            IF(
			                ISBLANK('Arrangement'[Ended]),
			                TRUE(),
			                'Arrangement'[Ended] >= CurrentStartDate
			            )
			        )
			    ),
			
			    IF(
			        CurrentStartDate > Today,
			        BLANK(),
			        CALCULATE(
			            MAXX(
			                ADDCOLUMNS(
			                    'Function Assignments',
			                    "EffectiveEnded", IF(ISBLANK(RELATED('Arrangement'[Ended])), Today, RELATED('Arrangement'[Ended]))
			                ),
			                [EffectiveEnded]
			            ),
			            NOT ISBLANK(Arrangement[Started]),
			            Arrangement[Started] <= CurrentEndDate,
			            IF(
			                ISBLANK('Arrangement'[Ended]),
			                TRUE(),
			                'Arrangement'[Ended] >= CurrentStartDate
			            )
			        )
			    )
			
			)
		formatString: Short Date
		lineageTag: fb33ac15-607e-454c-8940-c3532b67f934

	measure '# of Engaged Entities (NEW)' =
			
			
			CALCULATE(
			    DISTINCTCOUNT(Entity[PersonId]),
			    FILTER(
			        Entity,
			        [Entity Engagement Level] > 0
			    )
			)
		formatString: 0
		lineageTag: 9648f304-9232-43cc-a282-72f384eb2e8a

	column FamilyId
		dataType: string
		displayFolder: _columns
		lineageTag: 9e6bc319-6b32-4874-b0d3-005077b363d4
		summarizeBy: none
		sourceColumn: FamilyId

		annotation SummarizationSetBy = Automatic

	column LocationId
		dataType: string
		displayFolder: _columns
		lineageTag: cfe25239-01f2-40b7-9a90-acfa70ba080d
		summarizeBy: none
		sourceColumn: LocationId

		annotation SummarizationSetBy = Automatic

	column 'Family Name'
		dataType: string
		displayFolder: _columns
		lineageTag: b23e5b0a-d126-4678-9a71-38ec18aa4882
		summarizeBy: none
		sourceColumn: Family Name

		annotation SummarizationSetBy = Automatic

	column Email
		dataType: string
		displayFolder: _columns
		lineageTag: 862659a1-372b-41f1-83ae-183a267061ce
		summarizeBy: none
		sourceColumn: Email

		annotation SummarizationSetBy = Automatic

	column 'Phone Number'
		dataType: string
		displayFolder: _columns
		lineageTag: 9fcbcdca-0dd1-41ef-bbc5-0a32f287811f
		summarizeBy: none
		sourceColumn: Phone Number

		annotation SummarizationSetBy = Automatic

	column 'Address Line 1'
		dataType: string
		displayFolder: _columns
		lineageTag: 1361ce88-2882-48c9-a069-840ee560c91d
		summarizeBy: none
		sourceColumn: Address Line 1

		annotation SummarizationSetBy = Automatic

	column 'Address Line 2'
		dataType: string
		displayFolder: _columns
		lineageTag: 3004db58-1488-406b-9f5f-946296263159
		summarizeBy: none
		sourceColumn: Address Line 2

		annotation SummarizationSetBy = Automatic

	column City
		dataType: string
		displayFolder: _columns
		lineageTag: 772c485f-54b3-4e4c-b97b-2c4a6336adcb
		summarizeBy: none
		sourceColumn: City

		annotation SummarizationSetBy = Automatic

	column County
		dataType: string
		displayFolder: _columns
		lineageTag: 1d769877-b981-4f47-9050-07cbf291d5c3
		summarizeBy: none
		sourceColumn: County

		annotation SummarizationSetBy = Automatic

	column State
		dataType: string
		displayFolder: _columns
		lineageTag: 980edc7f-b09e-4cb9-b374-8fe7ad9ace77
		summarizeBy: none
		sourceColumn: State

		annotation SummarizationSetBy = Automatic

	column PostalCode
		dataType: string
		displayFolder: _columns
		lineageTag: 76f8d028-c87f-404e-8ffa-c94d695c5b8d
		summarizeBy: none
		sourceColumn: PostalCode

		annotation SummarizationSetBy = Automatic

	column HomeChurch
		dataType: string
		displayFolder: _columns
		lineageTag: 233df190-e0d7-4a4a-ba57-73e15c575bfe
		summarizeBy: none
		sourceColumn: HomeChurch

		annotation SummarizationSetBy = Automatic

	column 'First Name'
		dataType: string
		displayFolder: _columns
		lineageTag: 19032d1c-f69c-4fb1-b9ec-6da7b34341bc
		summarizeBy: none
		sourceColumn: First Name

		annotation SummarizationSetBy = Automatic

	column 'Last Name'
		dataType: string
		displayFolder: _columns
		lineageTag: a182b468-2952-4172-a8f1-0ac27440da8f
		summarizeBy: none
		sourceColumn: Last Name

		annotation SummarizationSetBy = Automatic

	column Ethnicity
		dataType: string
		displayFolder: _columns
		lineageTag: 3c58c5c6-d1f9-4601-9b49-cba7713e679d
		summarizeBy: none
		sourceColumn: Ethnicity

		annotation SummarizationSetBy = Automatic

	column DateOfBirth
		dataType: dateTime
		formatString: Long Date
		displayFolder: _columns
		lineageTag: 4b14e7ab-d4ca-45c1-8a2b-55ae99d61955
		summarizeBy: none
		sourceColumn: DateOfBirth

		variation Variation
			isDefault
			relationship: ef63f3fe-04ee-4288-a9ac-f2f0a7b0d90d
			defaultHierarchy: LocalDateTable_de2c3251-3f42-4917-b1a3-c8994b5b4a55.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Full Name'
		dataType: string
		displayFolder: _columns
		lineageTag: bd311439-7c66-4ceb-8a12-11de38faa3de
		summarizeBy: none
		sourceColumn: Full Name

		annotation SummarizationSetBy = Automatic

	column Age = DATEDIFF(Entity[DateOfBirth], UTCNOW(), YEAR)
		formatString: 0
		displayFolder: _columns
		lineageTag: 33196aab-cb09-4889-b68c-74b4773dac85
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

		annotation __PBI_SemanticLinks = [{"LinkTarget":{"TableName":"Entity","TableItemName":"Age (bins)","ObjectType":4},"LinkType":"UsedInGroup"}]

	column 'Adult or Child' = IF(ISBLANK(Entity[Age]), BLANK(), IF(Entity[Age]>= 18, "Adult", "Child"))
		displayFolder: _columns
		lineageTag: 65775017-7f5a-451c-aca1-00d5e3e17723
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Age (bins)' =
			IF(
				ISBLANK('Entity'[Age]),
				BLANK(),
				INT('Entity'[Age] / 5) * 5
			)
		formatString: 0
		displayFolder: _columns
		lineageTag: 487e8f57-6086-42b7-aec8-42e60a6a9898
		summarizeBy: none

		extendedProperty GroupingMetadata =
				{
				  "binningMetadata": {
				    "binSize": {
				      "unit": 0,
				      "value": 5.0
				    }
				  },
				  "groupedColumns": [
				    {
				      "Column": {
				        "Expression": {
				          "SourceRef": {
				            "Entity": "Entity"
				          }
				        },
				        "Property": "Age"
				      }
				    }
				  ],
				  "version": 0
				}

		annotation GroupingDesignState = {"Version":0,"Sources":[{"Name":"e","Entity":"Entity"}],"GroupedColumns":[{"Column":{"Expression":{"SourceRef":{"Source":"e"}},"Property":"Age"}}],"BinItem":{"Expression":{"Floor":{"Expression":{"Column":{"Expression":{"SourceRef":{"Source":"e"}},"Property":"Age"}},"Size":5.0}}}}

		annotation SummarizationSetBy = Automatic

	column 'Participation Type' =
			
			
			VAR FamilyRoleApprovals = CALCULATE(
			    COUNTROWS('Role Approval'),
			    'Role Approval'[Entity Type] = "Family",
			    USERELATIONSHIP(Entity[FamilyId], 'Role Approval'[Entity Id]),
			    CROSSFILTER(Entity[PersonId], 'Role Approval'[Entity Id], None)
			)
			
			VAR IndividualRoleApprovals = CALCULATE(
			    COUNTROWS('Role Approval'),
			    'Role Approval'[Entity Type] = "Person")
			
			VAR Referrals = COUNTROWS(RELATEDTABLE(Referral))
			
			RETURN
			    IF(
			        FamilyRoleApprovals + IndividualRoleApprovals > 0,
			        "Volunteer Family",
			        IF(Referrals > 0,
			            "Partnering Family",
			            "Other"
			        )
			    )
		displayFolder: _columns
		lineageTag: f5cc564e-0e52-4725-b298-c4caf0e8c780
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column PersonType
		dataType: string
		displayFolder: _columns
		lineageTag: 6de05a4f-6d16-4087-bdf1-60023d7fa16c
		summarizeBy: none
		sourceColumn: PersonType

		annotation SummarizationSetBy = Automatic

	column OrganizationId
		dataType: string
		lineageTag: 55943f05-d46c-4007-88d5-40726a60fa20
		summarizeBy: none
		sourceColumn: OrganizationId

		annotation SummarizationSetBy = Automatic

	column PersonId
		dataType: string
		lineageTag: 4c0c2b4d-8c3c-4d13-b91b-c2542ce9a0ed
		summarizeBy: none
		sourceColumn: PersonId

		annotation SummarizationSetBy = Automatic

	partition Entity = m
		mode: import
		queryGroup: 'Consolidated Entities'
		source = ```
				let
				    Source = #"OData Live",
				
				    //Person Table:
				    PersonTable = Table.ExpandRecordColumn(
				        Table.ExpandRecordColumn(
				            Table.SelectColumns(
				                Source{[Name="Person", Signature="table"]}[Data],
				                {"Id", "FamilyId", "FirstName", "LastName", "Ethnicity", "DateOfBirth", "PersonType","Organization", "Location"}
				            ),
				            "Organization", {"Id"}, {"OrganizationId"}
				        ), "Location", {"Id"}, {"LocationId"}
				    ),
				
				    PersonRenamed = Table.RenameColumns(
				        PersonTable,
				        {"Id","PersonId"}
				    ),
				
				    // Family Table: 
				    FamilyTable = Table.ExpandRecordColumn(
				        Table.SelectColumns(
				            Source{[Name="Family", Signature="table"]}[Data],
				            {"Id", "Name", "PrimaryEmail", "PrimaryPhoneNumber", "PrimaryAddress", "HomeChurch"}
				        ),
				        "PrimaryAddress", {"Line1", "Line2", "City", "County", "State", "PostalCode"}
				    ),
				
				    //Combined Tables: 
				    CombinedTables = Table.Join(
				        PersonRenamed,
				        {"FamilyId"},
				        FamilyTable,
				        {"Id"},
				        JoinKind.LeftOuter
				    ),
				
				    #"Reordered Columns" = Table.ReorderColumns(CombinedTables,{"FamilyId", "Id", "LocationId", "Name", "PrimaryEmail", "PrimaryPhoneNumber", "Line1", "Line2", "City", "County", "State", "PostalCode", "HomeChurch", "PersonId", "FirstName", "LastName", "Ethnicity", "DateOfBirth", "PersonType"}),
				    #"Removed Columns" = Table.RemoveColumns(#"Reordered Columns",{"Id"}),
				    #"Renamed Columns" = Table.RenameColumns(#"Removed Columns",{{"Name", "Family Name"}, {"PrimaryEmail", "Email"}, {"PrimaryPhoneNumber", "Phone Number"}, {"Line1", "Address Line 1"}, {"Line2", "Address Line 2"}, {"FirstName", "First Name"}, {"LastName", "Last Name"}}),
				    #"Inserted Merged Column" = Table.AddColumn(#"Renamed Columns", "Full Name", each Text.Combine({[First Name], [Last Name]}, " "), type text)
				in
				    #"Inserted Merged Column"
				```

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

