table 'Export Contacts'
	lineageTag: 60ba141e-f35f-47f1-89c6-55e30f55efa7

	calculationGroup
		precedence: 2

		calculationItem Family = SELECTEDMEASURE()

		calculationItem Person = SELECTEDMEASURE()

	measure 'Dynamic Entity Name (Contacts)' = ```
			
			
			VAR Option = SELECTEDVALUE('Approvals by Entity'[Entity Type])
			
			RETURN SWITCH(
			    Option,
			    "Family", SELECTEDVALUE(Entity[Family Name]),
			    "Person", SELECTEDVALUE(Entity[Full Name])
			)
			
			```
		lineageTag: 6c40a732-8d76-4585-9c81-e048bb92f87c

	measure 'Referential Ids' =
			
			UNION(
			    SELECTCOLUMNS(Entity, "ID", Entity[FamilyId]),
			    SELECTCOLUMNS(Entity, "ID", Entity[PersonId])
			)
		lineageTag: ca26b563-c520-479c-b38b-a47032d38546

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Entity Type'
		dataType: string
		lineageTag: 798b8350-7e72-4ba1-bf35-9e3fce0f55d7
		sourceColumn: Name
		sortByColumn: Ordinal

	column Ordinal
		dataType: int64
		isHidden
		lineageTag: ff8163ef-30c6-4473-9fa7-e2715124d167
		sourceColumn: Ordinal

