table 'Function Assignments'
	lineageTag: 37dbfcb3-ae81-4dbe-b5b6-66fa9cff03bd

	column 'RLS Key'
		dataType: string
		lineageTag: a62545b1-4137-41f8-9d68-0900e4d3a38f
		summarizeBy: none
		sourceColumn: RLS Key

		annotation SummarizationSetBy = Automatic

	column Function
		dataType: string
		lineageTag: 079fd573-495f-401c-9b66-8edc8017fd7d
		summarizeBy: none
		sourceColumn: Function

		annotation SummarizationSetBy = Automatic

	column ArrangementId
		dataType: string
		lineageTag: 6e947cab-fb5f-4159-a6ed-a29555e29a34
		summarizeBy: none
		sourceColumn: ArrangementId

		annotation SummarizationSetBy = Automatic

	column OrganizationId
		dataType: string
		lineageTag: 3bf90936-d651-468d-84df-2c4743f87024
		summarizeBy: none
		sourceColumn: OrganizationId

		annotation SummarizationSetBy = Automatic

	column LocationId
		dataType: string
		lineageTag: 98fc42e1-37d8-4fd8-a295-0debe46dffc5
		summarizeBy: none
		sourceColumn: LocationId

		annotation SummarizationSetBy = Automatic

	column EntityId
		dataType: string
		lineageTag: 2d038b06-0aab-426f-a859-cc8c2f60c7ce
		summarizeBy: none
		sourceColumn: EntityId

		annotation SummarizationSetBy = Automatic

	partition 'Function Assignments' = m
		mode: import
		queryGroup: 'Consolidated Entities'
		source = ```
				let 
				    Source = #"OData Live",
				
				    // Family Function Assignments
				    Family = 
				    Table.SelectColumns(
				        Table.AddColumn(
				            Table.RenameColumns(
				                Table.AddColumn(
				                    Source{[Name="FamilyFunctionAssignments", Signature="table"]}[Data],
				                    "EntityType", each "Family"
				                ),
				                {{"FamilyId", "EntityId"}}
				            ),
				            "RLS Key", each Text.Combine({[OrganizationId], [LocationId]}, "-")
				        ),
				        {"OrganizationId", "LocationId", "RLS Key", "ArrangementId", "EntityId", "Function"}
				    ),
				    
				    // Individual Function Assignments
				    Person = 
				    Table.SelectColumns(
				        Table.AddColumn(
				            Table.RenameColumns(
				                Table.AddColumn(
				                    Source{[Name="IndividualFunctionAssignments", Signature="table"]}[Data],
				                    "EntityType", each "Person"
				                ),
				                {{"PersonId", "EntityId"}}
				            ),
				            "RLS Key", each Text.Combine({[OrganizationId], [LocationId]}, "-")
				        ),
				        {"OrganizationId", "LocationId", "RLS Key", "ArrangementId", "EntityId", "Function"}
				    ),
				
				    //Combined Table:
				    CombinedTables = Table.Combine({Family, Person})
				in
				    CombinedTables
				```

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

