table 'Function Assignments'
	lineageTag: eced6c92-2c6c-4731-9471-3ec38417408e

	column 'RLS Key'
		dataType: string
		lineageTag: 863adef9-1333-403c-b200-5089d4599ddf
		summarizeBy: none
		sourceColumn: RLS Key

		annotation SummarizationSetBy = Automatic

	column Function
		dataType: string
		lineageTag: d4127997-a5ce-43e5-84d2-a9b485c5f963
		summarizeBy: none
		sourceColumn: Function

		annotation SummarizationSetBy = Automatic

	column 'Entity UID'
		dataType: string
		lineageTag: 70e0c0df-7e9b-4bd6-8400-c64b6eaa19ec
		summarizeBy: none
		sourceColumn: Entity UID

		annotation SummarizationSetBy = Automatic

	column 'Entity Type'
		dataType: string
		lineageTag: 5bb02500-f2b3-407d-a36b-a9c04c26616a
		summarizeBy: none
		sourceColumn: Entity Type

		annotation SummarizationSetBy = Automatic

	column 'Arrangement ID'
		dataType: string
		lineageTag: 6b2d7590-bec7-43e8-ba50-1dd985dcad54
		summarizeBy: none
		sourceColumn: Arrangement ID

		annotation SummarizationSetBy = Automatic

	partition 'Function Assignments' = m
		mode: import
		queryGroup: Fact
		source = ```
				let
				    Source = #"OData Live",
				    FamilyFunctionAssignments = Source{[Name="FamilyFunctionAssignments", Signature="table"]}[Data],
				    IndividualFunctionAssignments = Source{[Name="IndividualFunctionAssignments", Signature="table"]}[Data],
				
				    // Family Transformations:
				    FamilyFunc = 
				        Table.SelectColumns(
				            Table.RenameColumns(
				                Table.AddColumn(
				                    Table.AddColumn(
				                        Table.AddColumn(
				                            FamilyFunctionAssignments,
				                            "RLS Key", each Text.Combine({[OrganizationId], [LocationId]}, "-")
				                        ),
				                        "Entity UID", each Text.Combine({[RLS Key], [FamilyId]}, "-")
				                    ),
				                    "Entity Type", each "Family"
				                ),
				                {{"ArrangementId", "Arrangement ID"}}
				            ),
				            {"RLS Key", "Entity UID", "Entity Type", "Arrangement ID", "Function"}
				        ),
				
				    // Person Transformations:
				    IndividualFunc = 
				        Table.SelectColumns(
				            Table.RenameColumns(
				                Table.AddColumn(
				                    Table.AddColumn(
				                        Table.AddColumn(
				                            IndividualFunctionAssignments,
				                            "RLS Key", each Text.Combine({[OrganizationId], [LocationId]}, "-")
				                        ),
				                        "Entity UID", each Text.Combine({[RLS Key], [PersonId]}, "-")
				                    ),
				                    "Entity Type", each "Person"
				                ),
				                {{"ArrangementId", "Arrangement ID"}}
				            ),
				            {"RLS Key", "Entity UID", "Entity Type", "Arrangement ID", "Function"}
				        ),
				
				    // Combined Tables:
				    FuncAssignments = Table.Combine(
				        {FamilyFunc, IndividualFunc}
				    )
				
				
				in
				    FuncAssignments
				```

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

