table Location
	lineageTag: 8b4ebd77-c4b0-42a5-93d7-a051b5863d3a

	column 'RLS Key'
		dataType: string
		lineageTag: 518385f7-1022-484f-aa61-3c53f35cd0ac
		summarizeBy: none
		sourceColumn: RLS Key

		annotation SummarizationSetBy = Automatic

	column Location
		dataType: string
		lineageTag: 02c86e9f-d4fb-4f28-b194-e03695bb6fca
		summarizeBy: none
		sourceColumn: Location

		annotation SummarizationSetBy = Automatic

	column Id
		dataType: string
		lineageTag: 21cf8ebc-50d3-4f02-9094-2fe85114b691
		summarizeBy: none
		sourceColumn: Id

		annotation SummarizationSetBy = Automatic

	partition Location = m
		mode: import
		queryGroup: Dimensions
		source = ```
				let
				    Source = #"OData Live",
				    Location = Source{[Name="Location", Signature="table"]}[Data],
				    LocationTransformed = 
				    Table.SelectColumns(
				        Table.RenameColumns(
				            Table.AddColumn(
				                Location,
				                "RLS Key", each Text.Combine({[OrganizationId], [Id]}, "-")
				            ),
				            {{"Name", "Location Name"}}
				        ),
				        {"RLS Key", "Location Name"}
				    ),
				    #"Renamed Columns" = Table.RenameColumns(LocationTransformed,{{"Location Name", "Location"}})
				
				in
				    #"Renamed Columns"
				```

	changedProperty = Name

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

