table Location
	lineageTag: 16a053ed-84f9-4826-879d-c70341fcdfb9

	column Id
		dataType: string
		isHidden
		isKey
		lineageTag: 77c826a0-a516-4e55-a8d7-4c91f12da689
		summarizeBy: none
		sourceColumn: Id

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Location
		dataType: string
		lineageTag: c9741d87-8c80-4ebf-98af-bfb5b2942cc9
		summarizeBy: none
		sourceColumn: Location

		annotation SummarizationSetBy = Automatic

	partition Location-73b11de1-d894-44a9-b32e-4ba98f7ecfb2 = m
		mode: import
		queryGroup: 'Model Queries'
		source = ```
				let
				    Source = #"OData Live",
				    SourceTable = Source{[Name="Location",Signature="table"]}[Data],
				
				    Locations = 
				    Table.SelectColumns(
				        Table.RenameColumns(
				            SourceTable,
				            {{"Name", "Location"}}
				        ),
				        {"Id", "Location"}
				    )
				        
				in
				    Locations
				```

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

