table Location
	lineageTag: 2a8d5d04-e25c-46ad-8a29-b1b85c1c570f

	column 'RLS Key'
		dataType: string
		lineageTag: 53f24189-2a83-4576-b9a1-7eff6b42968d
		summarizeBy: none
		sourceColumn: RLS Key

		annotation SummarizationSetBy = Automatic

	column Id
		dataType: string
		lineageTag: 64108431-f469-4e56-b29f-7d786af2ab2c
		summarizeBy: none
		sourceColumn: Id

		annotation SummarizationSetBy = Automatic

	column 'Location PK'
		dataType: string
		lineageTag: dafc31cd-d1cd-40fc-990d-c44a222426bd
		summarizeBy: none
		sourceColumn: Location PK

		annotation SummarizationSetBy = Automatic

	column Location
		dataType: string
		lineageTag: 6156588d-d0ac-4882-9f4d-86f94b8944e2
		summarizeBy: none
		sourceColumn: Location

		annotation SummarizationSetBy = Automatic

	partition Location = m
		mode: import
		queryGroup: 'Model Queries'
		source = ```
				let
				    Source = #"OData Live",
				    SourceTable = Source{[Name="Location",Signature="table"]}[Data],
				
				    Locations = 
				    Table.SelectColumns(
				        Table.AddColumn(
				            Table.AddColumn(
				                Table.RenameColumns(
				                    SourceTable,
				                    {{"Name", "Location"}}
				                ),
				                "RLS Key", each Text.Combine({[OrganizationId], [Id]}, "-")
				            ),
				            "Location PK", each Text.Combine({[RLS Key], [Location]}, "-")
				        ),
				        {"RLS Key", "Id", "Location PK", "Location"}
				    )
				        
				in
				    Locations
				```

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

