table Location
	lineageTag: 9b78184e-f905-4fe7-8a9c-7b1b82d0da8c

	column 'RLS Key'
		dataType: string
		lineageTag: 8ad230f8-c550-405a-8203-c929a3086632
		summarizeBy: none
		sourceColumn: RLS Key

		annotation SummarizationSetBy = Automatic

	column Id
		dataType: string
		lineageTag: 21cf8ebc-50d3-4f02-9094-2fe85114b691
		summarizeBy: none
		sourceColumn: Id

		annotation SummarizationSetBy = Automatic

	column Location
		dataType: string
		lineageTag: 97b1dc7f-4d67-4527-bf14-7423eb64f770
		summarizeBy: none
		sourceColumn: Location

		annotation SummarizationSetBy = Automatic

	partition Location = m
		mode: import
		queryGroup: 'Model Queries'
		source = ```
				let
				    Source = #"OData Live",
				    SourceTable = Source{[Name="Location",Signature="table"]}[Data],
				
				    Locations = 
				    Table.SelectColumns(
				        Table.AddColumn(
				            Table.RenameColumns(
				                SourceTable,
				                {{"Name", "Location"}}
				            ),
				            "RLS Key", each Text.Combine({[OrganizationId], [Id]}, "-")
				        ),
				        {"RLS Key", "Id", "Location"}
				    )
				in
				    Locations
				```

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

