table Referrals
	lineageTag: 827d0073-eb4c-48e2-b555-4d0ceee7ce76

	column ReferralId
		dataType: string
		lineageTag: c85494b1-4f59-4fdb-8b7e-3872c464fc2e
		summarizeBy: none
		sourceColumn: ReferralId

		annotation SummarizationSetBy = Automatic

	column CreatedAtUtc
		dataType: dateTime
		formatString: General Date
		lineageTag: 10d8a3f3-fcfa-4d63-8df9-2106733e9b49
		summarizeBy: none
		sourceColumn: CreatedAtUtc

		annotation SummarizationSetBy = Automatic

	column Title
		dataType: string
		lineageTag: 2aea02b2-ca85-4a23-ae67-348af516819c
		summarizeBy: none
		sourceColumn: Title

		annotation SummarizationSetBy = Automatic

	column Status
		dataType: string
		lineageTag: 1360bfa6-06fb-49eb-a44f-9c8db0f1b9fb
		summarizeBy: none
		sourceColumn: Status

		annotation SummarizationSetBy = Automatic

	column Comment
		dataType: string
		lineageTag: 5ba095b0-fa96-4e02-ae6a-aea2142549c3
		summarizeBy: none
		sourceColumn: Comment

		annotation SummarizationSetBy = Automatic

	column AcceptedAtUtc
		dataType: dateTime
		formatString: General Date
		lineageTag: d52a4d03-5991-44a1-8ddc-577726467fad
		summarizeBy: none
		sourceColumn: AcceptedAtUtc

		annotation SummarizationSetBy = Automatic

	column ClosedAtUtc
		dataType: dateTime
		formatString: General Date
		lineageTag: d48e174b-55cd-4fa7-bcf1-467d89cbccdb
		summarizeBy: none
		sourceColumn: ClosedAtUtc

		annotation SummarizationSetBy = Automatic

	column CloseReason
		dataType: string
		lineageTag: 2f837136-a8a7-42af-805b-9e6fcf1f86d1
		summarizeBy: none
		sourceColumn: CloseReason

		annotation SummarizationSetBy = Automatic

	column 'RLS Key'
		dataType: string
		lineageTag: 8100b894-a686-472e-8b13-dbaca1dbcadd
		summarizeBy: none
		sourceColumn: RLS Key

		annotation SummarizationSetBy = Automatic

	column 'Family UID'
		dataType: string
		lineageTag: aa69459a-1de3-4605-98ad-c4ab9bab1407
		summarizeBy: none
		sourceColumn: Family UID

		annotation SummarizationSetBy = Automatic

	column 'Case UID'
		dataType: string
		lineageTag: a22a2e12-0fbd-4d0f-9653-ddf4bbdc3eb8
		summarizeBy: none
		sourceColumn: Case UID

		annotation SummarizationSetBy = Automatic

	partition Referrals = m
		mode: import
		queryGroup: Fact
		source = ```
				let
				    Source = #"OData Live",
				    Referral = Source{[Name="Referrals", Signature="table"]}[Data],
				
				    ReferralFinal = 
				    Table.SelectColumns(
				        Table.AddColumn(
				            Table.AddColumn(
				                Table.AddColumn(
				                    Referral,
				                    "RLS Key", each Text.Combine({[OrganizationId], [LocationId]}, "-")
				                ),
				                "Family UID", each Text.Combine({[RLS Key], [FamilyId]}, "-")
				            ),
				            "Case UID", each Text.Combine({[RLS Key], [CaseId]}, "-")
				        ),
				        {"RLS Key", "Family UID", "ReferralId", "Case UID", "CreatedAtUtc", "AcceptedAtUtc", "ClosedAtUtc", "Title", "Status", "Comment", "CloseReason"}
				    )
				
				
				in
				    ReferralFinal
				```

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

