table Referral
	lineageTag: d767a338-d9a5-4e00-8b61-2f6469d3aa63

	/// This measure counts the number of referrals opened during a given timeframe, including duplicate referrals for the same family during the same timeframe.
	measure '# of Referrals Opened' =
			COUNTROWS(
			    FILTER(
			        Referral,
			        AND(
			            Referral[Opened] >= [Selected Timeframe Start],
			            Referral[Opened] <= [Selected Timeframe End]
			        )
			    )
			)
		formatString: 0
		lineageTag: 9629d58a-d07b-4c7a-8853-0a6f66904884

		changedProperty = IsHidden

	/// A family was referred during the selected timeframe if one or more referrals was opened for them during that timeframe. This measure does not count duplicate referrals for the same family during a given timeframe.
	measure '# of Families Referred' =
			
			CALCULATE(
			    DISTINCTCOUNTNOBLANK(Referral[FamilyId]),
			    FILTER(
			        Referral,
			        AND(
			            Referral[Opened] >= [Selected Timeframe Start],
			            Referral[Opened] <= [Selected Timeframe End]
			        )
			    )
			)
		formatString: 0
		lineageTag: f8ef22d6-a7b1-4619-b6aa-f928642d95aa

	column Id
		dataType: string
		isHidden
		isKey
		displayFolder: _Columns
		lineageTag: 048d136e-c963-4efb-954c-117136ca81da
		summarizeBy: none
		sourceColumn: Id

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column FamilyId
		dataType: string
		isHidden
		displayFolder: _Columns
		lineageTag: cfbee179-9c41-46c7-912b-1e57e7a4259b
		summarizeBy: none
		sourceColumn: FamilyId

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Opened
		dataType: dateTime
		formatString: Short Date
		displayFolder: _Columns
		lineageTag: b1b56280-2e23-447e-8eb5-d75b32d2ad37
		summarizeBy: none
		sourceColumn: Opened

		variation Variation
			isDefault
			relationship: a5ae77fe-88aa-4706-bfd5-fdf99d014cf8
			defaultHierarchy: LocalDateTable_badf15b7-4811-4e5f-aee5-299aaab58eca.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Closed
		dataType: dateTime
		formatString: Short Date
		displayFolder: _Columns
		lineageTag: cdceaf22-4188-419b-81de-57ea5041da04
		summarizeBy: none
		sourceColumn: Closed

		variation Variation
			isDefault
			relationship: 61ed4f64-5da8-4039-89ee-4b2905a8923d
			defaultHierarchy: LocalDateTable_d64749d8-d763-4d50-94b8-a3acfe90e321.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column PrimaryReasonForReferral
		dataType: string
		lineageTag: 928e879d-7470-4e7e-bba1-6f6e12a14c5d
		summarizeBy: none
		sourceColumn: PrimaryReasonForReferral

		annotation SummarizationSetBy = Automatic

	column OrganizationId
		dataType: string
		lineageTag: 6b6c6730-f1d8-4329-98b0-6748f012affb
		summarizeBy: none
		sourceColumn: OrganizationId

		annotation SummarizationSetBy = Automatic

	column LocationId
		dataType: string
		lineageTag: f4f9f29f-0f0f-4286-a0f8-cf244d0a953d
		summarizeBy: none
		sourceColumn: LocationId

		annotation SummarizationSetBy = Automatic

	column 'RLS Key'
		dataType: string
		lineageTag: b4a44b4c-008d-49aa-a087-54ece637cca6
		summarizeBy: none
		sourceColumn: RLS Key

		annotation SummarizationSetBy = Automatic

	column 'Referral Source'
		dataType: string
		lineageTag: d0ea8f71-65ca-462c-8492-08265f63ed0e
		summarizeBy: none
		sourceColumn: Referral Source

		annotation SummarizationSetBy = Automatic

	column 'Close Reason'
		dataType: string
		lineageTag: f1bcff93-20cb-49d5-ad15-51627c6ec550
		summarizeBy: none
		sourceColumn: Close Reason

		annotation SummarizationSetBy = Automatic

	partition Referral-ae1a9126-4929-4d7f-8948-7409da4a474e = m
		mode: import
		queryGroup: 'Model Queries'
		source = ```
				let 
				    Source = #"OData Live",
				    SourceTable = Source{[Name="Referral", Signature="table"]}[Data],
				
				    Referral = 
				    
				    Table.SelectColumns(
				        Table.AddColumn(
				            Table.RenameColumns(
				                SourceTable,
				                {{"ReferralSource", "Referral Source"}, {"CloseReason", "Close Reason"}}
				            ),
				            "RLS Key", each Text.Combine({[OrganizationId], [LocationId]}, "-")
				        ),
				        {"Id", "OrganizationId", "LocationId", "RLS Key", "FamilyId", "Opened", "Closed", "Referral Source", "Close Reason", "PrimaryReasonForReferral"}
				    )
				        
				in
				    Referral
				```

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

