table Referrals
	lineageTag: 9e3a875e-349f-43da-84eb-8c636fdefbc9

	column 'RLS Key'
		dataType: string
		lineageTag: cd5525dd-e937-49df-b204-6c81e4fda7f7
		summarizeBy: none
		sourceColumn: RLS Key

		annotation SummarizationSetBy = Automatic

	column 'Referral ID'
		dataType: string
		lineageTag: 8186c11b-3aac-469e-9338-c5c6dbe09c2d
		summarizeBy: none
		sourceColumn: Referral ID

		annotation SummarizationSetBy = Automatic

	column 'Family UID'
		dataType: string
		lineageTag: 738b7dad-745e-4b9d-abf1-6e9042b82ab7
		summarizeBy: none
		sourceColumn: Family UID

		annotation SummarizationSetBy = Automatic

	column 'Family ID'
		dataType: string
		lineageTag: 324a14fb-9785-443c-9b0f-17c8e2cdfd72
		summarizeBy: none
		sourceColumn: Family ID

		annotation SummarizationSetBy = Automatic

	column Opened
		dataType: dateTime
		formatString: Long Date
		lineageTag: 3735aae9-a05e-45e2-b675-64e5b18b46bc
		summarizeBy: none
		sourceColumn: Opened

		variation Variation
			isDefault
			relationship: 1ab2206b-4a20-45f7-9023-09d98267b9ac
			defaultHierarchy: LocalDateTable_530a03d7-4545-4c50-b8bb-0eafd1c73faf.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Closed
		dataType: dateTime
		formatString: Long Date
		lineageTag: 731a711a-6cf1-4553-98be-25be1f1b4b11
		summarizeBy: none
		sourceColumn: Closed

		variation Variation
			isDefault
			relationship: c4be420d-f6cc-4943-8cbf-0f4f29d6fea4
			defaultHierarchy: LocalDateTable_fde1edd6-5eb1-4a41-b6af-f79f35fa348f.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Referral Source'
		dataType: string
		lineageTag: 9ec71218-11b8-4ae6-a43b-42a01cbbef9b
		summarizeBy: none
		sourceColumn: Referral Source

		annotation SummarizationSetBy = Automatic

	column 'Close Reason'
		dataType: string
		lineageTag: ac057b4d-f637-493e-ad3e-e4d72feb95da
		summarizeBy: none
		sourceColumn: Close Reason

		annotation SummarizationSetBy = Automatic

	column 'Primary Reason for Referral'
		dataType: string
		lineageTag: ae7e18ff-b6f6-4a22-aa8b-8389894dd252
		summarizeBy: none
		sourceColumn: Primary Reason for Referral

		annotation SummarizationSetBy = Automatic

	partition Referrals = m
		mode: import
		queryGroup: Fact
		source = ```
				let
				    Source = #"OData Live",
				    Referral = Source{[Name="Referral", Signature="table"]}[Data],
				    ReferralTransformed = 
				
				    Table.SelectColumns(
				        Table.RenameColumns(
				            Table.AddColumn(
				                Table.AddColumn(
				                    Referral,
				                    "RLS Key", each Text.Combine({[OrganizationId], [LocationId]}, "-")
				                ),
				                "Family UID", each Text.Combine({[RLS Key], [FamilyId]})
				            ),
				            {{"Id", "Referral ID"}, {"FamilyId", "Family ID"}, {"ReferralSource", "Referral Source"}, {"CloseReason", "Close Reason"}, {"PrimaryReasonForReferral", "Primary Reason for Referral"}}
				        ),
				        {"RLS Key", "Referral ID", "Family UID", "Family ID", "Opened", "Closed", "Referral Source", "Close Reason", "Primary Reason for Referral"}
				    )
				
				
				
				
				in
				    ReferralTransformed
				```

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

