table 'RLS Location User - Entity'
	lineageTag: 196bef88-706f-4131-bba1-e355518720a5

	column UserId
		dataType: string
		lineageTag: 39ad2e51-a3d0-45a2-9025-793b5dc3c4d2
		summarizeBy: none
		sourceColumn: UserId

		annotation SummarizationSetBy = Automatic

	column OrganizationId
		dataType: string
		lineageTag: fa1e6228-9b4e-4fd4-a048-7044e5aad7d2
		summarizeBy: none
		sourceColumn: OrganizationId

		annotation SummarizationSetBy = Automatic

	column LocationId
		dataType: string
		lineageTag: 2caaa747-edd7-4753-9eef-87d64f474c7c
		summarizeBy: none
		sourceColumn: LocationId

		annotation SummarizationSetBy = Automatic

	column 'RLS Key'
		dataType: string
		lineageTag: ac88b04e-9158-455f-85b2-419f458281b5
		summarizeBy: none
		sourceColumn: RLS Key

		annotation SummarizationSetBy = Automatic

	partition 'RLS Location User - Entity' = m
		mode: import
		queryGroup: RLS
		source =
				let
				    Source = #"OData Live",
				    LocationUserAccess_table = Source{[Name="LocationUserAccess",Signature="table"]}[Data],
				    #"Added Custom" = Table.AddColumn(LocationUserAccess_table, "RLS Key", each Text.Combine({[OrganizationId], [LocationId]}, "-")),
				    #"Removed Duplicates" = Table.Distinct(#"Added Custom")
				in
				    #"Removed Duplicates"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

