table 'RLS Location User - Community'
	lineageTag: ad97e9c3-5a9b-4286-8286-7a3b3c2b6419

	column UserId
		dataType: string
		lineageTag: cfa65435-8735-40fa-a564-3fc556cc2c6c
		summarizeBy: none
		sourceColumn: UserId

		annotation SummarizationSetBy = Automatic

	column OrganizationId
		dataType: string
		lineageTag: 47186f36-1b57-4206-9732-008206f575d6
		summarizeBy: none
		sourceColumn: OrganizationId

		annotation SummarizationSetBy = Automatic

	column LocationId
		dataType: string
		lineageTag: ea42349f-202e-4296-ae3f-dfc55f00be40
		summarizeBy: none
		sourceColumn: LocationId

		annotation SummarizationSetBy = Automatic

	column 'RLS Key'
		dataType: string
		lineageTag: c528c6df-f09f-4bcf-8e75-a27528e004ca
		summarizeBy: none
		sourceColumn: RLS Key

		annotation SummarizationSetBy = Automatic

	partition 'RLS Location User - Community' = m
		mode: import
		queryGroup: RLS
		source =
				let
				    Source = #"OData Live",
				    LocationUserAccess_table = Source{[Name="LocationUserAccess",Signature="table"]}[Data],
				    #"Added Custom" = Table.AddColumn(LocationUserAccess_table, "RLS Key", each Text.Combine({[OrganizationId], [LocationId]}, "-")),
				    #"Removed Duplicates" = Table.Distinct(#"Added Custom")
				in
				    #"Removed Duplicates"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

