table 'RLS Location User - Role'
	lineageTag: 148d9c98-2c42-433d-b9fb-cbf549f9919a

	column UserId
		dataType: string
		lineageTag: d6d2f05d-ffee-436c-a024-e0a0819fbf7f
		summarizeBy: none
		sourceColumn: UserId

		annotation SummarizationSetBy = Automatic

	column OrganizationId
		dataType: string
		lineageTag: 13b1c1de-4e77-44d8-a511-33cf475b67ee
		summarizeBy: none
		sourceColumn: OrganizationId

		annotation SummarizationSetBy = Automatic

	column LocationId
		dataType: string
		lineageTag: 06af6103-b69c-4d19-bcd3-3a70abbc6926
		summarizeBy: none
		sourceColumn: LocationId

		annotation SummarizationSetBy = Automatic

	column 'RLS Key'
		dataType: string
		lineageTag: e57b9997-7b5b-44a4-b2af-e601bbb69b9b
		summarizeBy: none
		sourceColumn: RLS Key

		annotation SummarizationSetBy = Automatic

	partition 'RLS Location User - Role' = m
		mode: import
		queryGroup: RLS
		source =
				let
				    Source = #"OData Live",
				    LocationUserAccess_table = Source{[Name="LocationUserAccess",Signature="table"]}[Data],
				    #"Added Custom" = Table.AddColumn(LocationUserAccess_table, "RLS Key", each Text.Combine({[OrganizationId], [LocationId]}, "-")),
				    #"Removed Duplicates" = Table.Distinct(#"Added Custom")
				in
				    #"Removed Duplicates"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

