table 'RLS Location User - Locations'
	lineageTag: 3eb27047-01ff-4ea6-896d-2e949e7bc73c

	column UserId
		dataType: string
		lineageTag: a7f17970-a02b-4641-9a65-c07e7aeb1e62
		summarizeBy: none
		sourceColumn: UserId

		annotation SummarizationSetBy = Automatic

	column OrganizationId
		dataType: string
		lineageTag: 1adafcb6-b8b1-4f0e-a267-2578be7d17e1
		summarizeBy: none
		sourceColumn: OrganizationId

		annotation SummarizationSetBy = Automatic

	column LocationId
		dataType: string
		lineageTag: 6284542e-e77e-4f71-9c0e-acef3a2c37c1
		summarizeBy: none
		sourceColumn: LocationId

		annotation SummarizationSetBy = Automatic

	column 'RLS Key'
		dataType: string
		lineageTag: 8bcc77a9-3705-4cf1-8b27-709ef70ba55a
		summarizeBy: none
		sourceColumn: RLS Key

		annotation SummarizationSetBy = Automatic

	partition 'RLS Location User - Locations' = m
		mode: import
		queryGroup: RLS
		source =
				let
				    Source = #"OData Live",
				    LocationUserAccess_table = Source{[Name="LocationUserAccess",Signature="table"]}[Data],
				    #"Added Custom" = Table.AddColumn(LocationUserAccess_table, "RLS Key", each Text.Combine({[OrganizationId], [LocationId]}, "-")),
				    #"Removed Duplicates" = Table.Distinct(#"Added Custom")
				in
				    #"Removed Duplicates"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

