table RLS
	lineageTag: 1e937af2-258c-44d6-ad23-78399a7d9847

	column 'RLS Key'
		dataType: string
		lineageTag: 44e4313f-f069-4ab7-9f6d-6eba269abb50
		summarizeBy: none
		sourceColumn: RLS Key

		annotation SummarizationSetBy = Automatic

	column UserId
		dataType: string
		lineageTag: ede6eafc-16c9-45e6-90e3-6e0f2d903129
		summarizeBy: none
		sourceColumn: UserId

		annotation SummarizationSetBy = Automatic

	column OrganizationId
		dataType: string
		lineageTag: ce37c732-0cd2-4f6e-ace2-a79efb11331c
		summarizeBy: none
		sourceColumn: OrganizationId

		annotation SummarizationSetBy = Automatic

	column LocationId
		dataType: string
		lineageTag: 05d2f26a-f10b-4193-a2ff-27616724c840
		summarizeBy: none
		sourceColumn: LocationId

		annotation SummarizationSetBy = Automatic

	partition RLS = m
		mode: import
		queryGroup: RLS
		source = ```
				let
				    Source = #"OData Live",
				    RLS = 
				    Table.SelectColumns(
				        Table.AddColumn(
				            Source{[Name="LocationUserAccess", Signature="table"]}[Data],
				            "RLS Key", each Text.Combine({[OrganizationId], [LocationId]}, "-")
				        ),
				        {"RLS Key", "OrganizationId", "LocationId", "UserId"}
				    )
				
				in
				    RLS
				```

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

