table Role
	lineageTag: 960f9fe2-c3cc-4543-9ef9-5a2b70f1f590

	column 'Role Name'
		dataType: string
		isKey
		displayFolder: _Columns
		lineageTag: d704ebe8-0cbc-4d24-a566-eadb44b16f45
		isDefaultLabel
		summarizeBy: none
		sourceColumn: Role Name

		annotation SummarizationSetBy = Automatic

	column OrganizationId
		dataType: string
		lineageTag: 5b588556-c5df-4549-be92-11cfa09d19bd
		summarizeBy: none
		sourceColumn: OrganizationId

		annotation SummarizationSetBy = Automatic

	partition Role-e671c74c-88c5-4c48-a3a5-404c5dec31f4 = m
		mode: import
		queryGroup: 'Model Queries'
		source =
				let
				    Source = #"OData Live",
				    Roles_table = Source{[Name="Role",Signature="table"]}[Data],
				    #"Removed Columns" = Table.RemoveColumns(Roles_table,{"OrganizationId"}),
				    #"Expanded Organization" = Table.ExpandRecordColumn(#"Removed Columns", "Organization", {"Id"}, {"Organization.Id"}),
				    #"Renamed Columns" = Table.RenameColumns(#"Expanded Organization",{{"Organization.Id", "OrganizationId"}, {"Name", "Role Name"}})
				in
				    #"Renamed Columns"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

