table 'Role Approvals'
	lineageTag: 90811375-696f-4ad0-9941-2e1af48bc4a6

	column 'RLS Key'
		dataType: string
		lineageTag: 77858b49-ac6f-4892-bc48-8bd62f9e6d40
		summarizeBy: none
		sourceColumn: RLS Key

		annotation SummarizationSetBy = Automatic

	column 'Entity Type'
		dataType: string
		lineageTag: ae951a29-7894-44c0-a0fc-3624c7931f47
		summarizeBy: none
		sourceColumn: Entity Type

		annotation SummarizationSetBy = Automatic

	column 'Entity UID'
		dataType: string
		lineageTag: 72cc5255-1daf-4227-b104-a21c5550e226
		summarizeBy: none
		sourceColumn: Entity UID

		annotation SummarizationSetBy = Automatic

	column EntityId
		dataType: string
		lineageTag: 04a62da9-9e70-4df9-af63-36142150a572
		summarizeBy: none
		sourceColumn: EntityId

		annotation SummarizationSetBy = Automatic

	column 'Role Name'
		dataType: string
		lineageTag: 8cce3bf0-cef2-42f3-b82e-ee8aacfaa610
		summarizeBy: none
		sourceColumn: Role Name

		annotation SummarizationSetBy = Automatic

	column Date
		dataType: dateTime
		formatString: Short Date
		lineageTag: 999480bf-10e4-420e-848d-44ec30a8ebb2
		summarizeBy: none
		sourceColumn: Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Approval Type'
		dataType: string
		lineageTag: 4b7da618-12c8-4615-b350-0863121b299b
		summarizeBy: none
		sourceColumn: Approval Type

		annotation SummarizationSetBy = Automatic

	column Status
		dataType: string
		lineageTag: 7462714d-009e-4ab8-9fb1-22c7e8b41907
		summarizeBy: none
		sourceColumn: Status

		annotation SummarizationSetBy = Automatic

	column 'Status Changed'
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 954287c6-cf6f-4e01-aaba-ffe455632f82
		summarizeBy: none
		sourceColumn: Status Changed

		annotation SummarizationSetBy = Automatic

	partition 'Role Approvals' = m
		mode: import
		queryGroup: Fact
		source = ```
				let
				    Source = #"OData Live",
				    RoleApproval = 
				
				        Table.SelectColumns(
				            Table.RenameColumns(
				                Table.AddColumn(
				                    Table.AddColumn(
				                        Source{[Name="RoleApprovals", Signature="table"]}[Data],
				                        "RLS Key", each Text.Combine({[OrganizationId], [LocationId]}, "-")
				                    ),
				                    "Entity UID", each Text.Combine({[RLS Key], [EntityId]}, "-")
				                ),
				                {{"StatusChanged", "Status Changed"}, {"RoleName", "Role Name"}, {"ApprovalType", "Approval Type"}, {"EntityType", "Entity Type"}}
				            ),
				            {"RLS Key", "Entity Type", "Entity UID", "EntityId", "Role Name", "Date", "Approval Type", "Status", "Status Changed"}
				        )
				
				in
				    RoleApproval
				```

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

