table 'Role Approval'
	lineageTag: 46da9e14-7769-40f8-9645-fc47e5f2407b

	measure '# Approval Tracker' =
			
			VAR Tracker =
			    SWITCH(
			        TRUE(),
			        ISINSCOPE('Role Approval'[Entity Name]),
			        VAR MaxDate = CALCULATE(
			            MAX('Role Approval'[Date]),
			            'Role Approval'[StatusChanged] = TRUE()
			        )
			        RETURN IF(ISBLANK(MaxDate), BLANK(), FORMAT(MaxDate, "YYYY-MM-DD")),
			
			        ISINSCOPE('Role Approval'[Role Name]),
			        FORMAT(CALCULATE(
			            DISTINCTCOUNT('Role Approval'[Entity Id]),
			            'Role Approval'[StatusChanged] = TRUE()
			        ), "0"),
			
			        ISINSCOPE('Role Approval'[Entity Type]),
			        FORMAT(CALCULATE(
			            DISTINCTCOUNT('Role Approval'[Entity Id]),
			            'Role Approval'[StatusChanged] = TRUE()
			        ), "0")
			    )
			
			RETURN
			    IF(ISBLANK(Tracker), BLANK(), Tracker)
		lineageTag: 590209fb-c050-4003-98c4-8671173f3212

	measure 'Volunteer Family Status Flag' = ```
			
			
			// INACTIVE OR ACTIVE DEFINITION:  
			// Inactive = only 'inactive' or 'denied'
			// Blank = no role approval
			// Active = anything other than 'inactive' or 'denied'
			
			VAR StartDate = [Selected Timeframe Start] 
			VAR EndDate = [Selected Timeframe End]
			
			VAR FamilyInactive = 
			    CALCULATE(
			        COUNTROWS('Role Approval'),
			        'Role Approval'[Date] >= StartDate && 'Role Approval'[Date] <= EndDate,
			        'Approval Status'[Status] IN {"Inactive", "Denied"},
			        'Role Approval'[Entity Type] = "Family",
			        USERELATIONSHIP(Entity[FamilyId], 'Role Approval'[Entity Id]),
			        CROSSFILTER(Entity[PersonId], 'Role Approval'[Entity Id], None)
			    )
			
			VAR FamilyActive = 
			    CALCULATE(
			        COUNTROWS('Role Approval'),
			        'Role Approval'[Date] >= StartDate && 'Role Approval'[Date] <= EndDate,
			        NOT 'Role Approval'[Status] IN {"Inactive", "Denied"},
			        'Role Approval'[Entity Type] = "Family",
			        USERELATIONSHIP(Entity[FamilyId], 'Role Approval'[Entity Id]),
			        CROSSFILTER(Entity[PersonId], 'Role Approval'[Entity Id], None)
			    )
			
			
			RETURN IF(FamilyActive > 0, "Active", IF(FamilyInactive > 0, "Inactive", IF(ISBLANK(FamilyActive + FamilyInactive), "No Role Approval")))
			
			```
		lineageTag: 26c1a021-747c-49d8-aaf5-a983bb323c80

	measure 'Volunteer Individual Status Flag' = ```
			
			
			// Inactive or Active Definition: 
			// Inactive = only 'inactive' or 'denied'
			// Blank = no role approval
			// Active = anything other than 'inactive' or 'denied'
			
			VAR StartDate = [Selected Timeframe Start] 
			VAR EndDate = [Selected Timeframe End]
			
			VAR PersonInactive = 
			    CALCULATE(
			        COUNTROWS('Role Approval'),
			        'Role Approval'[Date] >= StartDate && 'Role Approval'[Date] <= EndDate,
			        'Approval Status'[Status] IN {"Inactive", "Denied"},
			        'Role Approval'[Entity Type] = "Person"
			    )
			
			VAR PersonActive = 
			    CALCULATE(
			        COUNTROWS('Role Approval'),
			        'Role Approval'[Date] >= StartDate && 'Role Approval'[Date] <= EndDate,
			        NOT 'Role Approval'[Status] IN {"Inactive", "Denied"},
			        'Role Approval'[Entity Type] = "Person"
			    )
			
			RETURN IF(PersonActive > 0, "Active", IF(PersonInactive > 0, "Inactive", IF(ISBLANK(PersonActive + PersonInactive), "No Role Approval")))
			```
		lineageTag: 41e6fa73-ec85-4a75-9af2-47bc0c8bddb0

	column 'Entity Type'
		dataType: string
		lineageTag: 0fb1b97a-9aca-43be-aaaf-64c2d919515c
		summarizeBy: none
		sourceColumn: Entity Type

		annotation SummarizationSetBy = Automatic

	column Status
		dataType: string
		lineageTag: f18f85eb-7629-4b74-a64b-e1de51f329b2
		summarizeBy: none
		sourceColumn: Status

		annotation SummarizationSetBy = Automatic

	column 'Approval Type'
		dataType: string
		lineageTag: bab34ac0-c8ed-48a5-9e32-144a53b8afb1
		summarizeBy: none
		sourceColumn: Approval Type

		annotation SummarizationSetBy = Automatic

	column Date
		dataType: dateTime
		formatString: Short Date
		lineageTag: f8c87c7a-295b-4765-8dd9-23c751cb422e
		summarizeBy: none
		sourceColumn: Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column StatusChanged
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: c6a7afb2-a64e-45f9-8d08-812a0085a9dc
		summarizeBy: none
		sourceColumn: StatusChanged

		annotation SummarizationSetBy = Automatic

	column 'Entity Name' =
			COALESCE(
			    LOOKUPVALUE(Entity[Family Name], Entity[FamilyId], 'Role Approval'[Entity Id]),
			    LOOKUPVALUE(Entity[Full Name], Entity[PersonId], 'Role Approval'[Entity Id])
			)
		lineageTag: 33487ad4-e5c8-45c5-bdfc-261c58809382
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column OrganizationId
		dataType: string
		lineageTag: 9497c0bf-c108-4d9f-adb8-da4f3e9e630e
		summarizeBy: none
		sourceColumn: OrganizationId

		annotation SummarizationSetBy = Automatic

	column LocationId
		dataType: string
		lineageTag: 0c47a74a-83df-4e2b-abbb-c778c3ad3ee5
		summarizeBy: none
		sourceColumn: LocationId

		annotation SummarizationSetBy = Automatic

	column 'RLS Key'
		dataType: string
		lineageTag: 65cbb2c1-a71a-43c7-8c83-c8b49006b3e1
		summarizeBy: none
		sourceColumn: RLS Key

		annotation SummarizationSetBy = Automatic

	column 'Entity Id'
		dataType: string
		lineageTag: 2efcfb9c-0f78-4c9e-a598-7b8bc3f7a3ab
		summarizeBy: none
		sourceColumn: Entity Id

		annotation SummarizationSetBy = Automatic

	column 'Role Name'
		dataType: string
		lineageTag: bf8adb60-52a3-414b-87df-306ecdcc52ab
		summarizeBy: none
		sourceColumn: Role Name

		annotation SummarizationSetBy = Automatic

	partition 'Role Approval' = m
		mode: import
		queryGroup: 'Consolidated Entities'
		source = ```
				let
				    // Data source
				    Source = #"OData Live",
				
				    RoleApproval = 
				    Table.SelectColumns(
				        Table.RenameColumns(
				            Source{[Name="RoleApprovals", Signature="table"]}[Data],
				            {{"EntityType", "Entity Type"}, {"RoleName", "Role Name"},{"ApprovalType", "Approval Type"}, 
				            {"EntityId", "Entity Id"}, {"RlsKey", "RLS Key"}}
				        ),
				        {"RLS Key", "OrganizationId", "LocationId", "Entity Type", "Entity Id", "Role Name", "Date", "Approval Type", "Status", "StatusChanged"  }
				    )
				
				    
				in
				    RoleApproval
				```

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

