table Role
	lineageTag: 960f9fe2-c3cc-4543-9ef9-5a2b70f1f590

	column 'Role Name'
		dataType: string
		lineageTag: b7303532-6c4e-4a4b-83e7-0ad29753ffc8
		summarizeBy: none
		sourceColumn: Role Name

		annotation SummarizationSetBy = Automatic

	column OrganizationId
		dataType: string
		lineageTag: adae3153-d7bd-4bfb-a440-f20c0a2b55fa
		summarizeBy: none
		sourceColumn: OrganizationId

		annotation SummarizationSetBy = Automatic

	partition Role-e671c74c-88c5-4c48-a3a5-404c5dec31f4 = m
		mode: import
		queryGroup: 'Model Queries'
		source = ```
				let
				    Source = #"OData Live",
				    SourceTable = Source{[Name="Role", Signature="table"]}[Data],
				
				    Role = 
				    Table.SelectColumns(
				        Table.RenameColumns(
				            SourceTable,
				            {{"Name", "Role Name"}}
				        ),
				        {"OrganizationId", "Role Name"}
				    )
				in
				    Role
				```

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

