table Role
	lineageTag: a5a15efd-7639-4e75-a11f-7e21f671acbe

	column 'Role Name'
		dataType: string
		lineageTag: 99f25033-77d2-472e-aa78-36b450f50e70
		summarizeBy: none
		sourceColumn: Role Name

		annotation SummarizationSetBy = Automatic

	column 'Role UID'
		dataType: string
		lineageTag: 9a186480-99e2-4514-8056-9c1194fc149f
		summarizeBy: none
		sourceColumn: Role UID

		annotation SummarizationSetBy = Automatic

	partition Role = m
		mode: import
		queryGroup: Dimensions
		source = ```
				let
				    Source = #"OData Live",
				    SourceTable = Source{[Name="Role", Signature="table"]}[Data],
				
				    Role = 
				    Table.SelectColumns(
				        Table.AddColumn(
				            Table.RenameColumns(
				                SourceTable,
				                {{"Name", "Role Name"}}
				            ),
				            "Role UID", each Text.Combine({[OrganizationId], [Role Name]}, "-")
				        ),
				        {"Role UID", "Role Name"}
				    )
				
				in
				    Role
				```

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

