name: Run PBI Inspector

on:
  push:
  pull_request:

jobs:
  run-inspector:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.0.x'

    - name: Install PBI Inspector
      run: dotnet tool install --global pbiinspector.cli

    - name: Run PBI Inspector on pbip file
      run: pbiinspector inspect CareTogether.pbip --output result.json

    - name: Upload result
      uses: actions/upload-artifact@v3
      with:
        name: pbiinspector-result
        path: result.json
