name: Run PBI Inspector

on:
  push:
  pull_request:

jobs:
  inspect:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install ts-node globally
        run: npm install -g ts-node typescript

      - name: Clone PBI Inspector V2
        run: git clone https://github.com/NatVanG/PBI-InspectorV2.git

      - name: Run PBI Inspector CLI
        working-directory: ./PBI-InspectorV2
        run: npx ts-node src/cli.ts inspect ../CareTogether.pbip --output ../result.json

      - name: Upload inspection result
        uses: actions/upload-artifact@v4
        with:
          name: pbi-inspector-result
          path: result.json
