name: Run PBI Inspector V2

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  pbi-inspector:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download PBI Inspector CLI
        run: |
          curl -L -o PBIInspectorCLI.zip https://github.com/NatVanG/PBI-InspectorV2/releases/download/v2.3/PBIRInspectorCLI.zip
          Expand-Archive PBIInspectorCLI.zip -DestinationPath PBIInspectorCLI

      - name: Run PBI Inspector CLI
        run: |
          ./PBIInspectorCLI/PBIRInspectorCLI.exe -fabricitem "./CareTogether.pbip" -rules "./rules/Base-rules.json" -formats "GitHub" -verbose true
