name: PBI Inspector Analysis

on:
  push:
    paths:
      - '*.pbip'
  pull_request:
    paths:
      - '*.pbip'

jobs:
  run-inspector:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install PBI Inspector
      run: |
        git clone https://github.com/NatVanG/PBI-InspectorV2.git pbi-inspector
        cd pbi-inspector
        npm install

    - name: Run PBI Inspector
      run: |
        cd pbi-inspector
        # Ajuste aqui o caminho para seu arquivo .pbip
        node index.js ../CareTogether.pbip --output ../pbi-inspector-report.json

    - name: Upload report artifact
      uses: actions/upload-artifact@v3
      with:
        name: pbi-inspector-report
        path: pbi-inspector-report.json
