name: Run PBI Inspector

on:
  push:
  pull_request:

jobs:
  inspect-pbip:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install PBI Inspector CLI globally
        run: npm install -g @natvang/pbi-inspector

      - name: Run PBI Inspector on CareTogether.pbip
        run: pbi-inspector inspect ./CareTogether.pbip --output result.json

      - name: Upload inspection results
        uses: actions/upload-artifact@v4
        with:
          name: pbiinspector-result
          path: result.json
