name: Power BI Inspector CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  run-inspector:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout your repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install required Python packages
        run: |
          python -m pip install --upgrade pip
          pip install jsonschema

      - name: Clone PBI-InspectorV2
        run: |
          git clone https://github.com/NatVanG/PBI-InspectorV2.git inspector

      - name: Run PBI Inspector
        run: |
          export PYTHONPATH=$PYTHONPATH:$(pwd)/inspector/src
          python -m pbi_inspector check CareTogether.pbip --fail-on-error --output-format text
