name: Run PBI Inspector

on:
  push:
  pull_request:

jobs:
  inspect-pbip:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Clone PBI Inspector V2
        run: git clone https://github.com/NatVanG/PBI-InspectorV2.git

      - name: Install PBI Inspector dependencies
        working-directory: ./PBI-InspectorV2
        run: npm install

      - name: Run PBI Inspector
        working-directory: ./PBI-InspectorV2
        run: |
          npx ts-node src/cli.ts inspect ../CareTogether.pbip --output ../result.json

      - name: Upload inspection results
        uses: actions/upload-artifact@v4
        with:
          name: pbiinspector-result
          path: result.json
