name: Power BI Inspector CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  run-inspector:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout your project repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Clone PBI-InspectorV2 repository
        run: |
          git clone https://github.com/NatVanG/PBI-InspectorV2.git inspector
          pip install -r inspector/requirements.txt

      - name: Run PBI Inspector on CareTogether.pbip
        run: |
          python inspector/check.py CareTogether.pbip --fail-on-error --output-format text
