name: Run PBI Inspector

on:
  push:
  pull_request:

jobs:
  inspect-pbip:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x'

      - name: Install PBI Inspector CLI
        run: dotnet tool install --global pbiinspector.cli

      - name: Run PBI Inspector on CareTogether.pbip
        run: pbiinspector inspect CareTogether.pbip --output result.json

      - name: Upload inspection results
        uses: actions/upload-artifact@v4
        with:
          name: pbiinspector-result
          path: result.json
